### ISSUE TITLE
[include plugin] PDF is rebuilt from cached files despite cache turned off

### ISSUE THREAD

**Issue by r0ckarong** [splitbrain/dokuwiki-plugin-dw2pdf#105]
First off, I have had caching turned off since I started customizing my exports.

I've set up some documents in my DW to be exported as PDF files by creating an "index" document and including pages into this document. 

I can now edit content in the included pages as much as I want and it shows up correctly in the wiki, when I try to export DW2PDF will always generate the same PDF unless the main index file is changed. Ideally I will never touch the index file again if I've set it up correctly.

Is there some way to have the cache for the PDF generator expire on this page when the rendered content (not the underlying syntax) changes? Or any other way I can keep this up to date without touching the index page?

It sounds somewhat similar to 
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/issues/28

But your solution there was to suggest turning of caching and this is not what is causing my problem.

This bug [#57](https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/issues/57) sounds like a similar issue but for PDF books.

**Comment by Klap-in** [comment]
Today it really fixed.
