### ISSUE TITLE
Wrap Plugin "onlyprint" is ignored

### ISSUE THREAD

**Issue by r0ckarong** [splitbrain/dokuwiki-plugin-dw2pdf#107]
This is a very weird issue. The first time I tried it with a simple example it worked fine. 
Now I'm trying to put something like this into my page

```
<WRAP noprint>This text is not visible in print</WRAP>

<WRAP onlyprint>This text is only visible in print.</WRAP>
```

The noprint works fine and is only displayed on the website. But 'onlyprint' is completely ignored and won't be written into the resulting PDF.

Update:
It doesn't make a difference if I use <WRAP> or <wrap> neither one works.

Update2:
This gets weirder. I've restored the version of a page where it initially worked. Now this doesn't work either.

Update3: 
It's rendered correctly in the XHTML output as

```
<!-- EDIT4 PLUGIN_WRAP_START [0-] --><div class="wrap_onlyprint plugin_wrap">
<p>
this should only be in the print version
</p>
</div><!-- EDIT5 PLUGIN_WRAP_END [0-] -->
```

**Comment by Klap-in** [comment]
```
===== Testseite =====

<WRAP noprint>
nur Bildschirmausgabe
</WRAP>
<WRAP onlyprint>
nur Druckausgabe
</WRAP>
```
This example works fine for me.
