### ISSUE TITLE
Delete external URL links from exported PDF

### ISSUE THREAD

**Issue by WiXZlo** [splitbrain/dokuwiki-plugin-dw2pdf#117]
How can I remove links to external resources (such as images) of the exported pdf?
In the exported pdf there are links to the original reference image. I can go on the original images from the pdf file, but I do not need this capability. I give pdf freelancers who do not need to know these things.

**Comment by Klap-in** [comment]
When you have feedback, please mention the examples you tried as well. Thanks.
