### ISSUE TITLE
Block elements within list elements not rendered

### ISSUE THREAD

**Issue by texnixe** [splitbrain/dokuwiki-plugin-dw2pdf#157]
I'm using the yalist plugin to be able to use block level elements within ordered and unordered list elements. Unfortunately, these elements don't get rendered within the generated pdf. I tried if it is possible to render block level elements within list items by inserting html tags, but that doesn't work either. Everything within the list elements is rendered without any line breaks.

Is there a solution?

**Comment by Klap-in** [comment]
This feature should be added to the upstream mPDF library, which is used by dw2pdf.
