### ISSUE TITLE
Fatal error: Class 'Doku_Renderer_xhtml' not found in renderer.php on line 15

### ISSUE THREAD

**Issue by nirujmohan** [splitbrain/dokuwiki-plugin-dw2pdf#159]
I installed the latest dw2pdf (18 dec 2014 update) and when I click on Export to pdf I get an error :

Fatal error: Class 'Doku_Renderer_xhtml' not found in renderer.php on line 15

Is it a problem with my installation ?

thanks, Niruj

**Comment by Klap-in** [comment]
Which version of DokuWiki do you have?

**Comment by Klap-in** [comment]
I see that only the last two versions of DokuWiki will load the Doku_Renderer_xhtml automatically by the rule at https://github.com/splitbrain/dokuwiki/blob/master/inc/load.php#L100

Can you consider updating your wiki installation please?

**Comment by nirujmohan** [comment]
I was using a 2013 version. Updated to the latest and now it all works perfectly. 

Thanks !

**Comment by fwolfst** [comment]
I have the same issue (using DokuWiki from ubuntu 14.04 repository, version 0.0.20131208-1) and I prefer to stay on that version, what can I do?

**Comment by splitbrain** [comment]
@fwolfst nothing. your version is too old.

**Comment by fwolfst** [comment]
Thanks for the answer, although its not the one i hoped for :)

**Comment by dam660** [comment]
In fact I had the same problem, and I cannot upgrade my DW version too.
What I did to fix it:

In the dw2pdf folder, then in the renderer.php file,  after this line ;
`if (!defined('DOKU_INC')) die(); ` 

Add this one:
`require_once (DOKU_INC.'inc/parser/xhtml.php'); `

This allows the plugin to work.

**Comment by fwolfst** [comment]
@dam660 Awesome! Thanks a bunch, confirm that it works for me too (after some very basic tests).
