### ISSUE TITLE
Messagebox

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [splitbrain/dokuwiki-plugin-dw2pdf#163]
Hi,

instead of a modification of the template to integrate a pdf-button, on specific wiki pages I have integrated buttons with a link that should generate a pdf (by url) respectively to the current page. But when clicking on this button the process of generating the pdf file takes a while and in this time the user doesn't have any feedback. So he thinks that he has to click once more and once more ... and at the end he will be a little bit frustrated. 
So I think of a possibility of a messagebox that shows the user that the process of creating the pdf has been started.
How could this be integrated into the plugin meaningfully?

Regards Juergen

**Comment by Klap-in** [comment]
I have no idea how this is possible in an easy manner. Is it not too complicated for a problem that is not common? Or has everybody such large wiki pages? 

I propose closing.

**Comment by Klap-in** [comment]
Or maybe you can also create a javascript popup at clicking the button.
