### ISSUE TITLE
Can't print image in PDF since update on 2014-12-18

### ISSUE THREAD

**Issue by Lo-chan** [splitbrain/dokuwiki-plugin-dw2pdf#166]
Hi,

I soon as I have updated the pluging with the last version on 2014-12-18, I can't see images in exported PDF files anymore.

Here's my config:
- Apache 2.4.7
- PHP : 5.4.31
- 2014-09-29 "Hrun"
- 2014-12-18 dw2pdf
- Images are all in JPG format

Same problem on all pages. Since it was working with old version, I've rolled back the changes.

Tried on different pages, with different ACL settings (@ALL in full access for this spacename for exemple).

When I update the plugin, I'm doing it manually by copying the file. I've also tried to delete the whole plugin folder before copying the the new folder.

Could you please help me? I really need the TOC new functionality.

Thanks in advance,

Lo-chan

**Comment by Klap-in** [comment]
Can you provide (an example version of) the wiki syntax that you uses and (an example of) the jpg-image that are affected by your issue? That allows us to try to reproduce it.

**Comment by Klap-in** [comment]
What kind of url do your wiki have? what are your rewrite settings?

**Comment by Klap-in** [comment]
Please test with last version of dw2pdf. If this has improved the situation please reopen.
