### ISSUE TITLE
Latest Plugin Brakes Site Config. Settings 4 Hrun

### ISSUE THREAD

**Issue by Sollo** [splitbrain/dokuwiki-plugin-dw2pdf#167]
Current version of DW2PDF plugin has some issue with plugin settings making Global Configuration Settings return blank page. This was not the issue with earlier versions. When plugin disabled, Config. Settings gets restored to normal operation.

Worth mentioning: Plugin installed manually, though every other option tested as well, with the same results.

**Comment by splitbrain** [comment]
I can not reproduce this and assume it's fixed already.
