### ISSUE TITLE
typography plugin's sp:pre (white-space: pre;) is not supported by mPDF library

### ISSUE THREAD

**Issue by multicode** [splitbrain/dokuwiki-plugin-dw2pdf#169]
## Description

As you see in the pictures below, the text rendering in the PDF version is so messy when compared to the HTML rendering of that code in dokuwiki (when the pages use a typography code). Also you see that the last character of telugu script is not correctly printed on the PDF.

In order to replicated this environment, you have to install the [typography](https://www.dokuwiki.org/plugin:typography) plugin, and then use my code from below.

To my observation, I think dw2pdf is not handling the parameter `sp:pre` which is in-turn a CSS parameter if you read the [typography](https://www.dokuwiki.org/plugin:typography) plugin's man page.
## Screen View (Dokuwiki View)

![screen-view](https://cloud.githubusercontent.com/assets/5868699/5980192/49a23d26-a8ae-11e4-9125-8fd8ec6ba38a.jpg)
## Export PDF View

![exportpdf-view](https://cloud.githubusercontent.com/assets/5868699/5980191/49a1b9e6-a8ae-11e4-9563-a53610367b4a.jpg)
## My Code

```
====== Test Page ======

<typo fs:160%; sp:pre;>
<fc Green>Colored English Script </fc>
Uncolored English Script

<fc Blue>డాక్యూ విక్కీ - Colored Telugu Script </fc>
డాక్యూ విక్కీ - Uncolored Telugu Script
</typo>
```

**Comment by Klap-in** [comment]
The `sp:pre` is converted to `white-space: pre;` by the typgraphy plugin.

This is included in the print version of the page, which is used by the dw2pdf plugin.
But, the dw2pdf uses the library mPDF, which doesn't support this css styling `white-space: pre;`

On short term, I don't expect an addition of support for this styling. 

Workarounds: 
- use line breaks like: ` \\ ` for line breaks.
- use a whiteline between text blocks would normally create `<p></p>` blocks in DokuWiki renderer. However by using one big `<typo> .. </typo>`, this splitting in separate `<p></p>` blocks is not performed. Workaround is applying `<typo> .. </typo>` around every section that needs whitelines. Or eventually double `\\ \\ `

**Comment by Klap-in** [comment]
Closing, because it should be fixed upstream at the mPDF library.
