### ISSUE TITLE
table alignment's default differ from xhtml renderer

### ISSUE THREAD

**Issue by jaller94** [splitbrain/dokuwiki-plugin-dw2pdf#172]
The defaults alignment of head table items is center but DokuWiki's default is left.
All syntax variations that don't set alignment explicitly cause a different layout in html and pdf.

![table_alignment](https://cloud.githubusercontent.com/assets/10872136/6318889/2a747458-baa8-11e4-958b-14f8fc995b7a.png)

**Comment by Klap-in** [comment]
Is this issue visible in the print preview (see print preview of your browser) of an article with a table?
Can you check that please?

If the print preview is already affected, it can be improved in DokuWiki, otherwise the dw2pdf plugin (or the library used for it (mPdf)) should be improved.

**Comment by jaller94** [comment]
The print previews display the same way usual browsing does. The dw2pdf plugin differs.
Tested on:
 - Firefox 35 on Android/ Ubuntu
 - Chrome 40 on Android/ Ubuntu
![table_alignment_print-preview](https://cloud.githubusercontent.com/assets/10872136/6338527/cff407c4-bbaf-11e4-8258-e688ecd95614.png)

**Comment by Klap-in** [comment]
Thanks for the feedback.
