### ISSUE TITLE
spacing between two tables missing

### ISSUE THREAD

**Issue by jaller94** [splitbrain/dokuwiki-plugin-dw2pdf#173]
Having a table following right after a table causes the tables to have no margin.
![2tables](https://cloud.githubusercontent.com/assets/10872136/6320502/8b699f7c-badf-11e4-92ff-91e49d2495dc.png)

**Comment by Klap-in** [comment]
thanks for the separated reports, however the same note as with your other issue:
Is this issue visible in the print preview (see print preview of your browser) of an article with a table?
Can you check that please?

**Comment by jaller94** [comment]
Yes, print previews are displaying it the same way the dw2pdf plugin does.
Tested on:
 - Firefox 35 on Android/ Ubuntu
 - Chrome 40 on Android/ Ubuntu
![2tables_print-preview](https://cloud.githubusercontent.com/assets/10872136/6338429/208fdeac-bbaf-11e4-832a-5fd2754a3399.png)

**Comment by Klap-in** [comment]
to be sure, you use the default 'dokuwiki' template, isn't?

**Comment by jaller94** [comment]
Yes, this can be reproduced on www.dokuwiki.org.

**Comment by splitbrain** [comment]
fixed upstream
