### ISSUE TITLE
request: tpl directory by namespace

### ISSUE THREAD

**Issue by jheidecker** [splitbrain/dokuwiki-plugin-dw2pdf#183]
Either built-in or as an option it would be nice to have the tpl match the namespace to create a tpl for each namespace. Eg:

action.php:737

``` php
                //added to match templates to namespace when available
                $params = array('do' => 'export_pdf','tpl' => getNS($ID));
                //$params = array('do' => 'export_pdf');
```

The above works for me, but I did not test with anything other than a single level of namespaces.

**Comment by MarcBeutler** [comment]
It would be great to get an option that I can include at the beginning of a page, e.g:

~~PDF-TPL:yourtemplate~~

**Comment by Klap-in** [comment]
Duplicate of #307
