### ISSUE TITLE
Replacement @DATE@ does not work with params in cover.html

### ISSUE THREAD

**Issue by kayser** [splitbrain/dokuwiki-plugin-dw2pdf#192]
I just modified header_odd.html to show a formatted date using @DATE(@DATE@, %d.%m.%Y)@ which works just fine. Then I tried that on cover.html which does not work, only the inner  @DATE@ will be replaced but not the outer one.

Any quick hints where to fix it? If yes, I will provide a patch...

**Comment by Klap-in** [comment]
This date replacement is part of page_depend_replacements() function see
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/master/action.php#L497

The while the cover is prepared in the load_template() function. 
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/master/action.php#L466

The DATE() replacement is not a real page dependent replacement. My proposal is to move it to a separate function (e.g. page_independent_replacements()..), and include the replacements from $replace in this function as well. 

Thanks for the effort in advance!

**Comment by Klap-in** [comment]
Tested:

This is not working, not in header and not at cover:
```
@Date@ 
@Date(@Date@, %d.%m.%Y)@ 
@Date(21-2-2012, %d.%m.%Y)@
```
This is working, both in header and at cover:
```
@DATE@ 
@DATE(@DATE@, %d.%m.%Y)@ 
@DATE(21-2-2012, %d.%m.%Y)@
```
So it appears that the commands are case-sensitive.
