### ISSUE TITLE
Plugins doesn't work and completly broke dokuwiki

### ISSUE THREAD

**Issue by geceo** [splitbrain/dokuwiki-plugin-dw2pdf#198]
I use dokuwiki from debian wheezy packages, here is the version reported by a dpkg -l:

0.0.20120125b-2+deb7u1

I installed dw2pdf manually by:
1/ Unpacking tarball to /var/lib/dokuwiki/lib/plugins
2/ Renaming the directory to dw2pdf

Then, a hit to any dokuwiki page just returns a blank document.
Here is the error logged by my webserver:

PHP Fatal error:  Call to a member function str() on a non-object in /var/lib/dokuwiki/lib/plugins/dw2pdf/action.php on line 696

Code at line 696 is:

        $this->exportConfig['pagesize'] = $INPUT->str('pagesize', $this->getConf('pagesize'), true);

I tried to add the following lines to my /etc/dokuwiki/local.php (debian specifics to override configuration):

$conf['pagesize'] = 'A4';
$conf['orientation'] = 'portrait';

But it doesn't solved my issue.

Please, note that installing other plugins this way worked.

**Comment by splitbrain** [comment]
You're running an outdated version of DokuWiki. The plugin is not compatible with that old version.
