### ISSUE TITLE
[plantuml plugin] generated images not embedded into pdf

### ISSUE THREAD

**Issue by emerout** [splitbrain/dokuwiki-plugin-dw2pdf#205]
Hi,

Plantuml generated images are displayed on html page.
Browser preview also display this images.

But they are not embedded into exported pdf with dw2pdf.

Please note that plantuml PNG images are generated by java.

**Comment by Klap-in** [comment]
Are the images included as existing image in the html?
Or are these dynamic images that are just generated if their url is called?

**Comment by emerout** [comment]
It seems that they are dynamic.
Here is the html tag for the image (show source in my browser) : 

`<img src="/lib/plugins/plantuml/img.php?width=0&amp;height=0&amp;title=PlantUML%20Graph&amp;align=&amp;version=2011-07-16&amp;md5=76181b0c0a7b835eba05519bf6f763f2" class="media" title="PlantUML Graph" alt="PlantUML Graph">`

**Comment by MarcBeutler** [comment]
Have got the same issue...
Interesting is, that I have 2 DokuWiki Installations, one on localhost and the other one on our webserver. If I create a PDF-Export on the localhost, everything is made correctly, but if I create a PDF-Export from the wiki on our webserver, the plantUML diagrams are not exported correctly (its only the icon if an image can't be found: blank page with a ret x in the middle).
I activated $this->showImageErrors = true; in the config.php file od dw2pdf/mpdf/ and get the following error:
mPDF error: IMAGE Error (https://********.ch/wiki/lib/plugins/plantuml/img.php?width=0&height=0&title=PlantUML%20Graph&align=center&version=2011-07-16&md5=b6c4cb7d53175ef2bef3801a7e7fd5fa): Could not find image file

On the wiki everything is shown correctly, but not in the export...

**Comment by MarcBeutler** [comment]
Any progress so far?

**Comment by davemidd** [comment]
It's working ok for me on a web server installation (Release 2015-08-10a "Detritus).
Let me know if there's anything I can do to help debug.

**Comment by MarcBeutler** [comment]
How can I debug this?

**Comment by davemidd** [comment]
The Extension Manager in Dokuwiki shows that there is an update available, even though the latest version is installed:

![image](https://cloud.githubusercontent.com/assets/1181083/14206879/30e23d1c-f80e-11e5-9df5-9974dfc91270.png)

**Comment by Klap-in** [comment]
Looks like it in principal working. Maybe you have to investigate if the dw2pdf can call via a http request your plantuml images.

Eventually the plantuml plugin can use the `dw2pdf://` pseudo protocal (https://www.dokuwiki.org/plugin:dw2pdf:exportsupport#fetch_images_without_http_request)
for storing the image itself, and providing the filesystem location to dw2pdf. But I think that for the most server configurations the use of the psuedo protocol is not needed.
