### ISSUE TITLE
Chaning of image quality or compression

### ISSUE THREAD

**Issue by Alex66955** [splitbrain/dokuwiki-plugin-dw2pdf#209]
Hey,

some large images are compressed to much in the pdf file. The result is a image with low quality.

Is there a paramter to set the image compression/quality?

Regards
Alex

**Comment by Klap-in** [comment]
There is no setting at the moment.

We use the library mPDF. Some documentation about how it handles images is at the page:
http://mpdf1.com/manual/index.php?tid=245

Probably these defaults don't fit for you, I guess.

In the generatePDF() function in the action.php file some of the settings of the mPDF library are set. See for code https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/master/action.php#L258

Maybe you could try some options for your self.

If you like that we test as well, please give a simple example of wiki page content that you like to export, and provide an (link to) large image that is representative for your case.

**Comment by Alex66955** [comment]
Thanks for the nice support.

I played a little with the image DPI settings in mPDF but this has no effects and is not the root issue. In the mPDF manual you sent me, I saw that the image size of the the HTML tag will be used to embed it in a PDF file. My image in dokuWiki has a original upload dimension of 7464x4951 but the embed settings are 650pixel "{{:[XXX]:[YYY].png?650|}}". This information will be used for conversion. 

The solution for me is to set the dimension of embedded images in dokuWiki higher, like 1300px. After, the rendered html page in dokuWiki look likes a bit ugly. Because the index bar on the right side takes to much space but the exported pdf file looks perfect.
![unbenannt](https://cloud.githubusercontent.com/assets/3258379/10038752/4ca71638-61ca-11e5-9ec8-cd8915ffccc0.png)

**Comment by Klap-in** [comment]
This image is blurred already, so not that useful for testing this case... it is?

**Comment by Klap-in** [comment]
Does it make a difference if you use .jpg images?

**Comment by Klap-in** [comment]
I did some tests. Depending on the image, the jpg format is sometimes nicer after scaling, than a png. But it depends also on how much scaling was applied. So maybe it useful to test some different formats, and different kind of scaling, and maybe it is worth to scale the image before uploading to the wiki to a size that exports better?
