### ISSUE TITLE
Online QR code doesn't seem to use DokuWiki proxy

### ISSUE THREAD

**Issue by surfermarty** [splitbrain/dokuwiki-plugin-dw2pdf#210]
Installed the plugin on a box that needs to use a proxy to get to the 'net, and if the QR code option is enabled, it takes ages, times-out and then produces the PDF with a broken link symbol.

DokuWiki is set to use a proxy, and plugins etc can be managed using it. I'm guessing this plugin doesn't pick up the proxy settings for the wiki, so the online QR generator can't be reached.

Will have a look to see if it's easy to fix, but in the meantime, thought it best to report the problem.

**Comment by Klap-in** [comment]
The html for the QR code is generated at this point in the code:
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/master/action.php#L529

By the mPDF this html is converted into a pdf.
We override the `_getImage()` function of this library, to let it use some DokuWiki functionality for downloading images.
See the `media_get_from_URL()` function in https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/master/DokuPDF.class.php#L80
This function is implemented at: https://github.com/splitbrain/dokuwiki/blob/master/inc/media.php#L2118
Which calls `media_image_download()`, and that function uses the `DokuHTTPClient` for downloading the media. That `DokuHTTPClient` should use the correct network settings as configured for DokuWiki so far I know.

My first impression is that some things are there that must let work you case, but maybe somewhere in this flow are flaws...

**Comment by surfermarty** [comment]
> On 30 Sep 2015, at 19:30, Gerrit Uitslag <notifications@github.com> wrote:
> 
> The html for the QR code is generated at this point in the code:
> https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/master/action.php#L529
> 
> By the mPDF this html is converted into a pdf.
> We override the _getImage() function of this library, to let it use some DokuWiki functionality for downloading images.
> See the media_get_from_URL() function in https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/master/DokuPDF.class.php#L80
> This function is implemented at: https://github.com/splitbrain/dokuwiki/blob/master/inc/media.php#L2118
> Which calls media_image_download(), and that function uses the DokuHTTPClient for downloading the media. That DokuHTTPClient should use the correct network settings as configured for DokuWiki so far I know.
> 
> My first impression is that some things are there that must let work you case, but maybe somewhere in this flow are flaws...
> 

DokuPDF.class.php line 88 - regexp fails so gets through to
DokuPDF.class.php line 93 - list($ext,$mime) = mimetype($file);
mimetype() where $file is “https://….” returns empty $ext and $mime.

Check for ‘is_external’ on line 134 is within an ‘if’ construct that
is only called if the mime type is ‘image’ - which it will never be
for an ‘https://...' $file

So $local never gets set, and it all falls through to the parent::
call, so your overriden function/method will never get called;
so there is no proxy support in DokuPDF.class.php

— so at this point, I’d say you need to update DokuPDF.class.php
  and move the check for ‘is_external’ outside of that check for
  the mimetype being ‘image’. Unless I’ve missed something, as
  I can’t see that ‘mimetype()’ actually retrieves the file from
  the URL?

By moving the ‘is_external’ check outside of the check for the ‘image’
mimetype, the call goes through to ‘media_get_from_URL in
‘inc/media.php’; which then ignores it, because my ‘$conf[‘fetchsize’]’
defaulted to 0.

Tweaking that, so ‘fetchsize’ is bigger than the response from googleapi,
it then gets as far as calling media_image_download, which creates the
HTTPClient object. The HTTPClient->get calls HTTPClient->sendRequest,
which gets down to the $this->_ssltunnel() call, and that method quietly
strips the ‘query’ from $request_url, so the final call to the googleapi
server is for the URL ‘/chart’ - without the rest of the query code.

Reply isn’t an image, so the rest of the HTTPClient code rejects it.

Looks like there is a bug in the HTTPClient code too for handling SSL
URLs through a proxy. Will contact the DokuWiki folks about that one,
unless you can suggest anything else?

Cheers

marty

**Comment by surfermarty** [comment]
> 
> Tweaking that, so ‘fetchsize’ is bigger than the response from googleapi,
> it then gets as far as calling media_image_download, which creates the
> HTTPClient object. The HTTPClient->get calls HTTPClient->sendRequest,
> which gets down to the $this->_ssltunnel() call, and that method quietly
> strips the ‘query’ from $request_url, so the final call to the googleapi
> server is for the URL ‘/chart’ - without the rest of the query code.
> 

Updating the ‘HTTPClient.php’ code so it preserves the ‘query’ in
_ssltunnel() then fixes the problem, and I can now get QR codes
via a proxy.

I’ve reported the bug with HTTPClient on the dokuwiki mailing list;
will see what happens.

Cheers

marty

**Comment by splitbrain** [comment]
issue has been fixed in HTTPClient
