### ISSUE TITLE
Can't update this plugin

### ISSUE THREAD

**Issue by trebmuh** [splitbrain/dokuwiki-plugin-dw2pdf#214]
Going to the extension manager: ?do=admin&page=extension , I can see that there is an update for a 2015-09-02 version. When clicking to the update button, Dokuwiki tell me that there is an error : "Impossible to create the temp folder for downloading" (wild and wuick translation from French "Impossible de créer le dossier temporaire pour le téléchargement.") and then, this plugin is not updated.
Dokuwiki release : Release 2015-08-10a "Detritus"
Thanks in advance.

**Comment by trebmuh** [comment]
Any idea here ?

**Comment by splitbrain** [comment]
is your data/tmp folder writable? can other plugins be updated?

**Comment by trebmuh** [comment]
hi @splitbrain and thanks for your answer.
my data/tmp is drwxr-sr-x and other plugins can be updated.

Could that be because my dokuwiki root directory is named "doc/" and not "dokuwiki/" ?

Let me know if I can provide some other information.

**Comment by trebmuh** [comment]
@splitbrain : am I right to assume that my conf is good?

**Comment by splitbrain** [comment]
closing this in favor of #219
