### ISSUE TITLE
Export to pdf : get a blank page

### ISSUE THREAD

**Issue by impactJL** [splitbrain/dokuwiki-plugin-dw2pdf#215]
Hello
i have successfuly installed the dw2pdf plugins. It works well on simple pages.
I have a page with image and toggle. It seems that it doesn't work.
I am  redirected to a blak page, with  this url : http://XXX.XXX.XX.XXX/dokuwiki/doku.php?id=wiki:<pagenmae>&do=export_pdf
i have the same issue with pdfbook.
I have refresh the cache
Could you help me ?
regards

**Comment by splitbrain** [comment]
http://doku.wiki/faq:blankpage

**Comment by impactJL** [comment]
Hello
i solved the problem
it was due to a time limit in the php.ini
So the solution : 
- open the php.ini
- increase the value of max_execution_time and max_input_time
regards
