### ISSUE TITLE
PHP7 requires compatible function signatures in mPDF and the renderer

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki-plugin-dw2pdf#217]
Received by email on 22 december 2015 12:34

Bonjour,
 
Je me permets de vous contacter afin de vous signaler la présence d’erreurs dans le plugin dw2pdf que vous maintenez pour dokuwiki.
 
En effet, lors de l’installation de la version 7 de PHP (centos x64 / php-fpm / dépôt rémi collet), des warning sont envoyés par votre plugin :
 
`<b>Warning</b>:  Declaration of DokuPDF::_getImage(&$file, $firsttime = true, $allowvector = true, $orig_srcpath = false) should be compatible with mPDF::_getImage(&$file, $firsttime = true, $allowvector = true, $orig_srcpath = false, $interpolation = false) in <b>/data/www/wiki/lib/plugins/dw2pdf/DokuPDF.class.php</b> on line <b>20</b><br />`
`<br />`
`<b>Warning</b>:  Declaration of renderer_plugin_dw2pdf::locallink($hash, $name = NULL) should be compatible with Doku_Renderer_xhtml::locallink($hash, $name = NULL, $returnonly = false) in <b>/data/www/wiki/lib/plugins/dw2pdf/renderer.php</b> on line <b>15</b><br />`
`<br />`
`<b>Warning</b>:  Declaration of renderer_plugin_dw2pdf::emaillink($address, $name = NULL) should be compatible with Doku_Renderer_xhtml::emaillink($address, $name = NULL, $returnonly = false) in <b>/data/www/wiki/lib/plugins/dw2pdf/renderer.php</b> on line <b>15</b><br />
`
 
PHP 7 possède une détection des types des variables plus poussée et à le (bon ou mauvais) gout de remonter des warning en cas d’erreurs.
 
Bonne fête à vous,

**Comment by AnaelMobilia** [comment]
Hello,

The configuration was centos 7 / php-fpm 7 / dokuwiki 2015-08-10a "Detritus"

Regards
