### ISSUE TITLE
Incorrect bookmark structure in exported pdf file

### ISSUE THREAD

**Issue by MarcBeutler** [splitbrain/dokuwiki-plugin-dw2pdf#218]
Hi there

I've got the problem that the bookmarks don't have the correct structure in an exported pdf file. Headings with the same level on the dokuwiki page are suddenly displayed as a sub-chapter of the previous heading...

E.g: I have 3 numbered headings: 1. Overview, 2. General Requirements, 3. Protocol. All of the have sub-chapters which are also numbered. Those 3 headings should all be on the same level, also as bookmarks...the problem now is, that some of them, for example 3. Protocol is displayed as a sub-chapter of the heading 2. General Requirements...
I have a screenshot attached that shows th problem.
![incorrecttoc](https://cloud.githubusercontent.com/assets/9272813/12329217/8ba27472-badf-11e5-8371-53b867ae78a5.png)

Does anyone have an idea what the problem could be?

Thanks for the help!

**Comment by radicarl** [comment]
Same Here.
Using Version 2015-06-10.

Simple Example:
`====== Spielplatz ======
===== Überschrift 1. Ordnung =====
==== Überschrift 2. Ordnung ====

===== Überschrift 1. Ordnung =====
==== Überschrift 2. Ordnung ====
=== Überschrift 3. Ordnung ===

===== Überschrift 1. Ordnung =====
`
table of contents in the wiki:
![screenshot131](https://cloud.githubusercontent.com/assets/1108495/18712524/26781bf6-800f-11e6-8a4f-bf8ad45c8aac.png)

table of contents in the generated pdf
![screenshot132](https://cloud.githubusercontent.com/assets/1108495/18712552/498ddde2-800f-11e6-8d66-83b40116bbe6.png)

**Comment by radicarl** [comment]
Same with Version 2016-04-17

**Comment by radicarl** [comment]
think i got it solved:
in the renderer.php
`    function header($text, $level, $pos) {
        if(!$text) return; //skip empty headlines
        global $ID;

        $hid = $this->_headerToLink($text, true);
        $check = false;
        $pid = sectionID($ID, $check);
        $hid = $pid . '__' . $hid;

            // add PDF bookmark
        $bookmark = '';
        $bmlevel = $this->actioninstance->getExportConfig('maxbookmarks');
        if($bmlevel && $bmlevel >= $level){
            // PDF readers choke on invalid nested levels

            if ($this->lastheadlevel == -1)
                $this->lastheadlevel = $level;

            $step = $level - $this->lastheadlevel;

            if ($step > 0)
                $this->current_bookmark_level += 1;
            else if ($step <0)  {
                // replace the commented Line with the following
                // $this->current_bookmark_level -= 1;
                $this->current_bookmark_level += $step;
                if ($this->current_bookmark_level < 0)
                    $this->current_bookmark_level = 0;
            }

            $this->lastheadlevel = $level;

            $bookmark = '<bookmark content="'.$this->_xmlEntities($text).'" level="'.($this->current_bookmark_level).'" />';
        }
`
You have to go back the difference between the current and the last level. += instead of -= because $step is already negative. 

The otherway is okay, because you can't have a header level 3 with out having a header level 2 somewhere before in the document. But a level 1 header may follow directly after a level 3 header
