### ISSUE TITLE
update fail of version 2015-09-02

### ISSUE THREAD

**Issue by walterbe** [splitbrain/dokuwiki-plugin-dw2pdf#219]
Hi,

I am using Release 2015-08-10a "Detritus"
And have this plugin installed. I get the message there an update; version 2015-09-02

When it try to update by clicking on the update button after a long wait I get;
"Het is niet mogelijk het bestand te downloaden: https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master"
( can not download the file )

But when request the url I do get a download. When I try to install the downloaded tar.gz  using the GUI for manual install it just keeps "working, loading ..." without end. And so does not work also.

The old plugin works fine, so there is no real problem for me. Just wanted to inform you about this.

**Comment by trebmuh** [comment]
Thanks for reporting, I'm feeling less alone. Hi, I've got the same issue and did report it already here : https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/issues/214

**Comment by blacklord049** [comment]
Same here

**Comment by splitbrain** [comment]
Technically this seems to be a problem with the extension manager in DokuWiki and not the plugin itself. But let's continue the debugging here first.

So far I got different problem descriptions:

- @walterbe says the plugin can't be downloaded (via extension manager)
- @walterbe says a manual upload of the plugin fails
- @trebmuh says there is a problem with creating the temporary folder for unpacking
- @blacklord049 gives absolutely no info

So, there a couple of things I want to know from all of you first:

- what PHP version are you running?
- what DokuWiki version are you running?
- can you install other plugins hosted at github through the extension manager (eg. the gallery plugin)?
- do you get any PHP errors in your error log (See http://doku.wiki/bugs)?
- have you tried to completely remove the plugin (delete lib/plugin/dw2pdf) and then do a new install?
- when doing a manual upload (Tab "Manual Install" and then upload the tar.gz file) does the upload finish and then the browser hangs? Or does the upload fail already?
- Can you try installing from https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/archive/master.zip?

**Comment by blacklord049** [comment]
First i got a "tar.php" PHP timeout error. Second try, i get the "_unable to download the file https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master_" message on the configuration page. You'll find the required information below :

* Apache Server 2.4.18 x86 (Windows Server 2008 R2).
* PHP Version : 7.0.3.
* DokuWiki : Release Detritus, 2015-08-10a.
* Yes.
* Timeout error (-> "tar.php") while writing the file. I think it was due to my server timeout setting. 
* In fact my problem is not the update because this is the first time I'm using the plugin.
* Install from URL -> unable to download the file.

**Comment by trebmuh** [comment]
* PHP: 5.4.45
* dokuwiki: detritus
* yes
* PHP errors: I've got no access to
* yes: "Impossible de télécharger le fichier : https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master" (unable to download file: ...)
* "There was a file copy error while attempting to install files for directory dw2pdf: the disk could be full or file access permissions may be incorrect. This may have resulted in a partially installed plugin and leave your wiki installation unstable" (the browser hangs for a while (a few minutes) and then, gives the error message)
* same as above

@splitbrain : given that the tarball for this extension is about 50M, would there is any possibility that this is too large and we got a timeout? Would there is then a possibility of importing by hand (ie: ssh) this tar.gz somewhere on the dokuwiki subfolder for dw2pdf and then, start the installation from here (bypassing the download step) ?

HTH

**Comment by trebmuh** [comment]
@walterbe : ping.

**Comment by trebmuh** [comment]
@walterbe : ping ping :)

**Comment by walterbe** [comment]
thanks for ping. It still does not work for me. Will report about it tomorrow.

**Comment by blacklord049** [comment]
Still does not work to with the latest version, I had to download the full tar and manually put its content into the plugins folder.

**Comment by Klap-in** [comment]
My impression sofar is that this issue is cause by the large file size of the download. See also
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/issues/194
There a solution would be to create a separate download for the fonts.

**Comment by trebmuh** [comment]
@Klap-in : sounds reasonable to me

**Comment by walterbe** [comment]
_-  what PHP version are you running?_

5.6 native.   I have the option to change it to 5.3, 5.4, 5.5 and 7.0

_-  what DokuWiki version are you running?_

Release 2015-08-10a "Detritus"

_-  can you install other plugins hosted at github through the extension manager (eg. the gallery plugin)?_

I install the plugin Gallery Plugin by Andreas Gohr, version of 2016-01-24 by means of the build in extension manager:  Plugin gallery werd succesvol geïnstalleerd  (= ok)  Did take a long time from my POV. A couple of minutes. 
_
- do you get any PHP errors in your error log (See http://doku.wiki/bugs)?_

I think I have found those logs. But the seem not to be updated live so all my experiments here are not listed. But the still report about also dw2pdf.  See attached file of it is of any use.

_- have you tried to completely remove the plugin (delete lib/plugin/dw2pdf) and then do a new install?_

I de-install the plugin by means of the extension manager. I login to the webserver and check the lib/plugin directory. There is no trace of  dw2pdf .

I do a new install by means of the extension manager. After about 2 minutes I get "request timed out". Internal server error 500. 

The interface indicates that the plugin is installed. But it gives an update notification.  And the "export to PDF" option is not available in the GUI. 

The directory dw2pdf now exist on the server. It contains many files. It contains 348 files,  in total 67,4 MB

I remove it. I confirm the directory is empty.  

_-  when doing a manual upload (Tab "Manual Install" and then upload the tar.gz file) does the upload finish and then the browser hangs? Or does the upload fail already?_

I try a manual install by means of the extension manager. (manual local download, 49,9MB) - It fails. No error. I just come again on the page to manually do an install. 

I try to upload the file using the media manager of my docuwiki-install. It worked. 

_- Can you try installing from https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/archive/master.zip?_

I try to do a manual install by means of url using that link. Request time out. Took a long time. I first download the file local and try to install it that way. It just comes back again to the install page. No error.

The dw2pdf is "installed". It shows up in the plugins , gives the message there is an update but does not work.  I press "update".  After a very long time ..."request timeout". 

I notice the presence of the button "switch on". So the plugin is disabled? I switch it on. Pressing the button does not result in a response. It does not work. 

Comments;

When I started with my experiments and the plugin was installed but not worked I got the the notice in the extension manager;
"getInfo() not implemented in action_plugin_dw2pdf and /home/gqowpzrh/public_html/lbc/lib/plugins//dw2pdf/plugin.info.txt not found.
Verify you're running the latest version of the plugin. If the problem persists, send a bug report to the author of the dw2pdf plugin."

... and this still there now. 

Thank you for trying to fix this.  A PDF export function is very important to have.

[error_log_walterbe.txt](https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/files/243685/error_log_walterbe.txt)

**Comment by tomtroughton** [comment]
Hello,
I hope I am adding this in the right place. XUbuntu 16.04. Most recent stable version. Original message was "Unable to download the file: https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master". I downloaded the plugin manually. Tried to install through the extension manager, but it just failed with no message. Had to change the group and read/write rule after I copied it into the plugins folder, then install php-mbstring php7.0-mbstring, and restart the apache server.
HTH, Tom

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

**Comment by Klap-in** [comment]
Let assume that the large download size, as also reported in #194 has caused these issue. Therefore I will close this as duplicate. Side note: probably connectivity has improved in general, because we do not see new issue reports on this issue.
