### ISSUE TITLE
PDF is corrupted at first request, good from cache

### ISSUE THREAD

**Issue by blacklord049** [splitbrain/dokuwiki-plugin-dw2pdf#224]
Hi, 

My dokuwiki uses the following plugins : 

- Bootstrap Wrapper.
- Note Plugin.
- Video Share Plugin.

Template : 

- Bootstrap3 with Bootswatch theme.

Server :

- Apache 2.4.18 (Windows).
- PHP 7.0.3.

Clicking the Export 2 PDF button starts a download. Until that point everything seems to be OK. But at the first request the file is corrupted even if it's opened or saved. Second request, the file is taken from cache and is readable. 

- Corrupted PDF : http://www.mediafire.com/download/g85j3i3t339l8ah/corrupt.pdf
- Readable PDF : http://www.mediafire.com/view/mla0c4bu1598r7s/not_corrupt.pdf

Looks like it's not the first time it happens : https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/issues/80

Note : disabling cache makes the plugin unusable => PDF file always gets corrupted.

Thank you in advance,
Vincent

**Comment by splitbrain** [comment]
That's caused by #217
