### ISSUE TITLE
As of 16/03/2016 mpdf website seems to be shuttered, future of the project?

### ISSUE THREAD

**Issue by r0ckarong** [splitbrain/dokuwiki-plugin-dw2pdf#229]
A message on mpdf1.com reads

```
Updated 16/03/2016

This mPDF website is now closed down.

You can still download the latest mPDF package, and some example files from the site.

More information in due course...
```

Any ideas what this means and how it affects the future of this plugin?

**Comment by Klap-in** [comment]
Hmmm, the forum is also closed.
Maybe issues with the hosting induce this decision....?

There was already some activity on https://github.com/mpdf/mpdf
See also the issues of that account.

**Comment by splitbrain** [comment]
https://github.com/mpdf/mpdf/issues/104 suggests that there's at least continued effort by other developers.

**Comment by hucste** [comment]
May be by using tcpdf?
https://tcpdf.org
https://github.com/tecnickcom/tcpdf

**Comment by Klap-in** [comment]
mPDF library see now an steady progress, with recently the mPDF 7.0 release. And there is online documentation available at http://mpdf.github.io/
