### ISSUE TITLE
PDF not generating - page blank

### ISSUE THREAD

**Issue by withdefiance** [splitbrain/dokuwiki-plugin-dw2pdf#230]
Dear operator :) I hope you can help me out. I'm not a mega geek, so with my basic knowledge I try to build and run a new website. The idea is to post texts and books and to make it possible for people to run them as a PDF to also make them readable on for instance an e-reader or I-pad, phone whatever.

When I try the DW2PDF application it seems to work on the simple stuff. But when I for instance try to run it on this: http://anarchisme.nl/doku.php?id=namespace:abc_van_het_anarchisme its not working anymore. The PDF-export goes to a blank page which stalls it operation. The same is happening with the Bookbuilder (which is linked to such a text). Is there any chance to fix this (also from the website side)?

Thanks for your time. 

Tommy

**Comment by Klap-in** [comment]
for more info https://www.dokuwiki.org/faq:blankpage 
So please check your server logs
