### ISSUE TITLE
Should be able to de/select citation in configuration settings

### ISSUE THREAD

**Issue by nerfer** [splitbrain/dokuwiki-plugin-dw2pdf#234]
I had to dig around a bit to find how to turn that box on the end of each wiki page off, since I don't need it in my case.  It's easy enough to do, after doing a grep to find the /tpl/default section, but non-programmers would likely be stymied by that.  Maybe just having a general citation for the document following the TOC or something might be useful?

**Comment by Klap-in** [comment]
Then we can probably add more configurations for other parts, which probably more general complexity in this plugin. 

However, maybe it is an idea to collect some example templates at https://www.dokuwiki.org/plugin:dw2pdf or a on a sub page like: https://www.dokuwiki.org/plugin:dw2pdf:pdftemplates

**Comment by Klap-in** [comment]
I prefer adding of example PDF templates to 
https://www.dokuwiki.org/plugin:dw2pdf:pdftemplate 

Working with a PDF template is indeed a bit more work. But I guess worth the effort.
