### ISSUE TITLE
PAGEURL only works in citation, not header or footer

### ISSUE THREAD

**Issue by nerfer** [splitbrain/dokuwiki-plugin-dw2pdf#235]
Trying to use @PAGEURL@ (or @ID@) in the header of footer for exporting a book (not a page) will result in the URL of the originating page being used over and over, instead of the current page.  It does work just fine when included in citation.html.

**Comment by nerfer** [comment]
I guess the idea is that in many cases the header and footers are fixed for the whole document, except for page numbers.  Note that default/header_even.html displays this problem.

I'm a programmer, but not in PHP, so I'm kind of guessing. It looks like page_depend_replacements is called in the for loop for each HTML file only on template[cite].  Maybe if it was also done on template[html], which I think includes the headers and footers that would resolve it?

**Comment by Klap-in** [comment]
Sorry the headers are prepare once for the entire pdf.
The design choice is to set up one set of headers and footers (eventually even/odd) at once for the entire document. Therefore, if you use the bookcreator, you will have every where the same header, with as url the book manager page.

For the library used by dw2pdf it is technically possible to setup more headers/footers at the start, and select these later for the right pages, but that is not used in dw2pdf. Creating this automatically for every wiki article is cumbersome to program. There is not a placeholder for example for a 'chapter name' or 'chapter number' or in our case 'wiki article name/url/etc'. So for every next wiki article you have to create a new header/footer. 
To keep the plugin simpler and more robust we have chosen this current simpler solution.
