### ISSUE TITLE
dw2pdf cannot display German umlauts

### ISSUE THREAD

**Issue by rushhour** [splitbrain/dokuwiki-plugin-dw2pdf#240]
Hi,

Thanks for the plugin. 

I noticed the following problem:
When I insert German umlauts (ä, ö, ü) in a document , then there is a problem with the interpretation of this symbols.
## do=export_pdf&debughtml=text

`<p> Enthält grundlegende Einstellungen für den Thin Client unabhägig auf welche Collection der Thin Client zugreifen soll. <br/> Ist mit dem Verzeichnis /Thin Clients/IGEL UD W7+/ verknüpft.  </p>`

## do=export_pdf&debughtml=html

`<p> EnthÃ¤lt grundlegende Einstellungen fÃ¼r den Thin Client unabhÃ¤gig auf welche Collection der Thin Client zugreifen soll. <br/> Ist mit dem Verzeichnis /Thin Clients/IGEL UD W7+/ verknÃ¼pft. </p>`

Regards

**Comment by gamma** [comment]
I had the same problem, I changed the font and it worked again.

**Comment by Klap-in** [comment]
So there is a font that doesn't contain these umlauts? Which font did you use first?

**Comment by gamma** [comment]
Currently: dejavusans

**Comment by Mailaender** [comment]
Did you update https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/master/mpdf/mpdf.css accordingly?

**Comment by Klap-in** [comment]
I test a copy of your text in a DokuWiki setup with latest dw2pdf. 
do=export_pdf&debughtml=text, do=export_pdf&debughtml=html, and do=export_pdf work all as expected. So they show the text with umlauts.

Using the shipped PDF template 'default'. So the font family is the default:
```css
body {
  font-family: sans-serif;
}
```
I assume it is fixed. Please reopen if needed.
