### ISSUE TITLE
Translations within the PDF (tpl/citation.html: permanent link, last update...)

### ISSUE THREAD

**Issue by cpamcom** [splitbrain/dokuwiki-plugin-dw2pdf#243]
Translation is missing within the PDF.

I want the PDF to show "lien permanent" (permanent link) and "dernière mise-à-jour" (last update).
The file **dokuwiki-plugin-dw2pdf/tpl/default/citation.html** could integrate other languages?

**Comment by Klap-in** [comment]
I recommendate that you create a new template in the 'tpl/' folder. Just a copy of the 'default/' folder. Next you select in the configuration settings your new template. This template you can modify according your wishes. The default template is just a simple example, and at the first glance for me not worth the effort of localization...

**Comment by cpamcom** [comment]
Ok, thank you. When you make a localization I'll contribute!
