### ISSUE TITLE
Update to version 2016-04-17 failed

### ISSUE THREAD

**Issue by strahlc** [splitbrain/dokuwiki-plugin-dw2pdf#244]
Dw2Pdf plugin
Dokuwiki says: "Update: Version 2016-04-17 steht zum Download bereit."
(Translation: "Update: Version 2016-04-17 is available for download.")

When clicking update, I got the following error message:
"Download der Datei: https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master nicht möglich."
(Translation: "Download of file: https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master not possible.")

**Comment by ILPlais** [comment]
Same for me. Even if I download the file and try a manual installation.

**Comment by Klap-in** [comment]
Since the used library mPDF is updated to version 6 it has a download package of at least 50 MB. It appears that this creates a lot of strange problems.

See for proposed solution in #194.
