### ISSUE TITLE
ttf font not found on windows server 2012

### ISSUE THREAD

**Issue by micgro42** [splitbrain/dokuwiki-plugin-dw2pdf#246]
On a new install of Windows Server 2012 the pdf export fails immeadieately with the error-message 
`Not a TrueType font: version=0`

The default DokuWiki template is used. Copying the Arial fonts from the windows fonts directory to the mpdf ttf dir did not solve the problem. Neither was the relacement of `arial` -> `DejaVuSans` successful.

Going back to the fallback version of mpdf 5.7.4/mid-2015 as described on the [wikipage](https://www.dokuwiki.org/plugin:dw2pdf#features) however did solve the problems. However now the bookcreator-plugin fails to work correctly.

**Comment by Klap-in** [comment]
Eventually you could catch the html with the debug option:
https://www.dokuwiki.org/plugin:dw2pdf#how_to_collect_more_debug_info
From that it is probably simpler to reduce the html.
A newer version of mpdf is also available via composer, so simple to install for testing. I haven't had time for moving dw2pdf plugin to the composer setup.

**Comment by Klap-in** [comment]
@micgro42 how is the last version of dw2pdf behaving (that is using mpdf 7 development version)? 

(btw: mPDF 7.0 is recently released, do you may have the opportunity to update the mPDF library? 
You did some changes to the imageprocessing, could you have a look again, and see what is now the most handy approach for updating?)

**Comment by micgro42** [comment]
The bug occurred on a client's server. I no longer have access to that server, or Windows Server instances in general, so I cannot reproduce it. It might very well be fixed by the last upgrade.

As to mPDF7.0: maybe we can take a look at it in 2018.

**Comment by Klap-in** [comment]
Might be solved..
