### ISSUE TITLE
Export containing images shows broken image links.

### ISSUE THREAD

**Issue by dcbell** [splitbrain/dokuwiki-plugin-dw2pdf#247]
I am attempting to export a large portion of our wiki into PDF form. I'm using PDF Export option so siteexport_pdf gets selected as the render engine. When I do that, the images show broken link icons. The image is linked in the following format:

{{ :ns1:ns2:ns3:image.png?800 |}}

If I don't use the PDF Export option and just select dw2pdf, then the images work fine. But I prefer the layout of the siteexport_pdf. Any suggestions?

**Comment by Klap-in** [comment]
I discover for the first time that dw2pdf can be used via the Siteexport Plugin as well. I will try to reproduce this if I have free time.

**Comment by dcbell** [comment]
Any update on this?

**Comment by dcbell** [comment]
FYI, I tried using a JPG instead of PNG so I wouldn't have an alpha channel and I get the same results. Just a red X. I can access the image file directly in the browser, so that isn't the issue.

**Comment by Klap-in** [comment]
Sorry, I'm interested in have a look into this, but I'm also busy with other things at the moment. So sorry for the lack of response.

**Comment by Klap-in** [comment]
I can reproduce this in my wiki.
Looking at the code, to discover were these images are handled I see that Siteexport has its own code for intiating the pdf building , as well image handling. Please report an issue at its issue tracker.

This could be a related issue:
https://github.com/i-net-software/dokuwiki-plugin-siteexport/issues/53

**Comment by dcbell** [comment]
Sounds good. Thank you.
