### ISSUE TITLE
The dw2pdf delete from content

### ISSUE THREAD

**Issue by termih** [splitbrain/dokuwiki-plugin-dw2pdf#248]
I have this content

`<code java>`
`a = 0;`
`</code>`

After exporting to PDF this line:
     a = 0;

these will in the PDF document:
    a =;

Erased the '0' character.

The issue is resolved if this code:

`<code>`
`a = 0;`
`</code>`

The problem, therefore, the coloring is caused.

Specific sheet:
http://szit.hu/doku.php?id=oktatas:programoz%C3%A1s:programoz%C3%A1si_t%C3%A9telek:java_megval%C3%B3s%C3%ADt%C3%A1s

**Comment by bilbo-the-hobbit** [comment]
hello,

i got exactly the same issues it only replace the 0 inside the highlited code this is really a big issue, as it render some documentation completely useless after exporting them to pdf

in dokuwiki 
dn: olcDatabase=**{0}**config,cn=config

after pdf export
dn: olcDatabase=**{}**config,cn=config

so doc is then wrong and useless 

this is an important issue !

Cheers

**Comment by Klap-in** [comment]
Test with last update of dw2pdf show the zeros aren't deleted anymore. I expect that recent improvements in the mPDF library have solved your problem.
