### ISSUE TITLE
Installing on Detritus

### ISSUE THREAD

**Issue by boardtc** [splitbrain/dokuwiki-plugin-dw2pdf#249]
When I install via the Extension Manager I get the problem. I wonder if it installs when one is using a farm? The tmp directroy it looking for does not exist in the farm folder...

> Warning: fopen(/home/mysite/public_html/farm/food/data/tmp/d3386fcb06e5b0b5b4ef894093b64eca/dw2pdf/splitbrain-dokuwiki-plugin-dw2pdf-47496d3/mpdf/utils/UnicodeData.txt) [function.fopen]: failed to open stream: No such file or directory in /home/mysite/public_html/dokuwiki/vendor/splitbrain/php-archive/src/Tar.php on line 167
Unable to decompress the downloaded file. This maybe as a result of a bad download, in which case you should try again; or the compression format may be unknown, in which case you will need to download and install manually. Could not open file for writing: /home/mysite/public_html/farm/farm1/data/tmp/d3386fcb06e5b0b5b4ef894093b64eca/dw2pdf/splitbrain-dokuwiki-plugin-dw2pdf-47496d3/mpdf/utils/UnicodeData.txt
> 
> Warning: Cannot modify header information - headers already sent by (output started at /home/mysite/public_html/dokuwiki/vendor/splitbrain/php-archive/src/Tar.php:167) in /home/mysite/public_html/dokuwiki/inc/common.php on line 1818

**Comment by Klap-in** [comment]
Does removing everything and try to reinstall help? Sorry, so far no clues for us..
