### ISSUE TITLE
PDF stops showing images from some point of the document, also there is some linked text problem

### ISSUE THREAD

**Issue by greldinard** [splitbrain/dokuwiki-plugin-dw2pdf#255]
I have a DokuWiki document with about 450 lines of code. There are some links and some images referenced as well. Exporting it to PDF works fine. Except images are not shown anymore from about the middle of the document until the end.

And there is some ugly behaviour about the following text. It is turned into a link to the image in the DokuWiki. Looks about like that (normal text, broken image, broken image, following text is link to second image):

![dw2pdfissue_images_linked_text](https://cloud.githubusercontent.com/assets/15708478/22825350/ea93f298-ef8c-11e6-90de-3e4331cb8e11.png)

Anyone experienced similar behaviour? I already double checked the syntax of the code. Probably some parsing error?
Thanks!

**Comment by Klap-in** [comment]
Please create a sample syntax for others to test in their wiki.

**Comment by greldinard** [comment]
You could use the same code I posted at #256 just enter some images inside. I have about 6 in the first half of the document and about 8 others in the second half. The images in the second half are not shown in the PDF and then there is this weird text effect with the link to the image. I hope you can work with that.

**Comment by Klap-in** [comment]
Do you still see these issues in the last version of dw2pdf?
The underlying library mPDF has been updated, combined with some image handling fixes. So I hope it will work again.

**Comment by greldinard** [comment]
I hope I will have the opportunity to check it soon and then give some feedback...

**Comment by greldinard** [comment]
Ok, the good news is, that the creation of the PDF now is much faster than before. The bad news is, that the problem still exists (exact same behaviour). Thank you very much for your work anyhow!

**Comment by Klap-in** [comment]
What is your system setup? OS, version of webserver, etc
What is example wiki page that shows this behaviour? Can you provide an example picture as well.

**Comment by greldinard** [comment]
Trying to reproduce the error in the test document provided  in https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/issues/256 with images I observed, that the problem is caused by incorrect usage of external links. In the document there were two places where external links were declared as "[[https://example.org]] - as a link with text, without providing a link text. This seems to irritate the DokuWiki parser a lot. It took out the images from the first usage of such a link and also set the following section of the text completely to be a link to the image that is not displayed. Even though the page was always displayed correctly. This caused the described problems creating PDF. After removing the [s and ]s the PDF is perfectly fine! Sorry for the inconviniece and thanks for your work and thoughts. Is this probably something that could be fetched while processing the page for PDF-conversion?

**Comment by Klap-in** [comment]
Which exact links did fail and which did succeed?

[[https://example.org]] broken?
[[https://example.org|title]] good?

And where did you set the image?

**Comment by greldinard** [comment]
Yes, your assumption is correct. It was like:

```
bla bla bla [[https://example.com]] more bla bla. Even more bla bla bla.

{{ :scope:image?parameters | bla }}

Bla bla. This is the text following the image and it is completely a link to the image whilst the image is not being shown in the PDF file.
```

I hope it became a little bit clearer now.

**Comment by Klap-in** [comment]
Can you provide the exact parameters you use in the image syntax? 
I tried: `{{:members:john.jpg?direct&300| bla}}`

Please try to be precise as possible. 
Then it is easier for me to try to replicate it. So far I don't see the behaviour here. Thanks!
btw: What is your system setup? OS, version of webserver, etc
