### ISSUE TITLE
Incorrectly formatted text in Dokuwiki

### ISSUE THREAD

**Issue by WildWalkerGB** [splitbrain/dokuwiki-plugin-dw2pdf#257]
Hello All,

When I create a PDF in Dokuwiki, any text that is indented (so appears in a text box) has a much larger font size in the PDF than in Dokuwiki. This means any PDF I create is unreadable as they text formatting is destroyed.

Please see attached files.

Is there any configuration changes I can make to rectify this please?

Best regards,
Alan Walker.

![pdf format](https://cloud.githubusercontent.com/assets/26108992/23451751/33588428-fe59-11e6-9e11-848283720ed6.png)
![dokuwiki web format](https://cloud.githubusercontent.com/assets/26108992/23451750/335640a0-fe59-11e6-9d03-17684b4e31f0.png)

**Comment by Klap-in** [comment]
You can do your own styling by creating your own PDF template.
Please see https://www.dokuwiki.org/plugin:dw2pdf:pdftemplate
In the style.css of your PDF template you can add the styling.

**Comment by Klap-in** [comment]
The basic style included with dw2pdf is relatively simple.
Fontsize can be customized via a PDF template

A typical difference between a pdf and screen is that on screen you can have scrollable items, in pdfs not.
