### ISSUE TITLE
CSS for tables

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [splitbrain/dokuwiki-plugin-dw2pdf#264]
Hi,

I've tried to define CSS parameters for the table layout. But it doesn't have any effect on the file generation of the pdf. The CSS-code in userall.css as well as in style.css of my pdf template is
```
.table-bordered {
	border: 3px solid #dddddd;
	}
```
Best regards
Juergen

**Comment by Klap-in** [comment]
How do you add the "table-bordered" class to the tables in html?

**Comment by Klap-in** [comment]
Please reopen with more info.
