### ISSUE TITLE
images not showing in PDFs

### ISSUE THREAD

**Issue by cjohnsonuk** [splitbrain/dokuwiki-plugin-dw2pdf#267]
I get a little white doc icon with a red cross or nothing at all
similar to this post  :
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/issues/145
when exporting a dw to pdf except that the error I get relates to the image not being found.  Setting 
$this->showImageErrors = true ;
in 
/lib/plugins/dw2pdf/mpdf/config.php 

results in no pdf but the error

mPDF error: IMAGE Error (https://<hostname>/<rootdir>/lib/plugins/dw2pdf/tpl/default-wfc/../../../wrap/images/note/48/tip.png): Could not find image file

Yet apache will happily show this image.
I do have a matching version php56 and gd for php56 and User uploaded images (and wrap images) in the wiki pages appear in the PDF without an issue.  It only appears to be the icons included in the wrap plugin that do not appear.  I added wrap to the  config for dw2pdf but still no joy.

**Comment by cjohnsonuk** [comment]
tested with a completely clean dw install with just the default plugins (including wrap) and dw2pdf
Exporting the wiki:welcome page to pdf results in a pdf
... but it takes 2 minutes to create the export

adding an image results in a pdf with an image 
... but it takes 2 minutes to create the export

adding 2 wrap sections results in 2 outlines around the wrapped text (no fill, and no icon)

adding "wrap" to the plugins section of the dw2pdf configuration results in colour filled outlines around the wrapped text but no icons

Enabling  

[code]
$this->showImageErrors = true;
[/code]

in /lib/plugins/dw2pdf/mpdf/config.php

results in 

[code]
mPDF error: IMAGE Error (http://dev.welfarecall.com/wiki2/lib/plugins/wrap/images/note/48/important.png): Could not find image file
[/code]

But the image with this url will load in the browser. In the css style the image is shown as
[code]
 background-image: url(/wiki2/lib/plugins/wrap/images/note/48/important.png);

[/code]
Removing all images and wraps and exporting the default wiki:welcome results in this error

[code]
mPDF error: IMAGE Error (http://dev.welfarecall.com/wiki2/lib/images/interwiki/doku.gif): Could not find image file
[/code]

and again the image will load in the browser and appears to be the very tiny dokuwiki logo used to identify dokuwiki links (which was missing from the earlier pdfs)

Inspecting the page these images appear to be passed embedded into the css as base 64 encoded as a background image to the section/div applied to that text.

Removing all the [[doku>... ...]] links creates a PDF almost instantly so the delays appear to be related to the inability to "find" the images.

Creating my own transparent .png file and adding it to the wiki:welcome page works in the export so it doesn't appear to be a mpdf transparent image issue!  I even wrapped this in a simple wrap box with no icon and it works fine.  

It appears to be icons in plugins that cause the issue.

**Comment by Klap-in** [comment]
This error looks like an error of mPDF, the library that dw2pdf is using.
I do not get the precise cause of this kind of errors if handling pictures.

The annoying point is the lack of debug info when the error is thrown. 

At least: Thanks for reducing the scope of this issue!
I will see if I could reproduce it.

**Comment by micgro42** [comment]
@cjohnsonuk can you check if the error still occurs with the latest version of the dw2pdf plugin?

**Comment by cjohnsonuk** [comment]
I will do but it may be some time before I get a chance to a) remember what
the issue was, b) get time away from my current projects.  Thanks for your
interest in this though! :-)

Chris Johnson

**Comment by Klap-in** [comment]
Since images processing improvements in the upgrade to last version of mPDF, used in last version of dw2pdf, I assume this is solved. If not: please (re)open with an example.
