### ISSUE TITLE
filce copy error installing on Frusterick Manners

### ISSUE THREAD

**Issue by boardtc** [splitbrain/dokuwiki-plugin-dw2pdf#274]
Hi,

I have an installation of Release 2017-02-19b "Frusterick Manners" which is on a farm of 2. I tried to install DW2PDF and I get the error "There was a file copy error while attempting to install files for directory dw2pdf: the disk could be full or file access permissions may be incorrect. This may have resulted in a partially installed plugin and leave your wiki installation unstable "

On my admin extensions page it then says under DW2PDF: Update: New version 2016-04-17 is available.

Any help to get the plugin installed is much appreciated.

Thanks,

Tom.

**Comment by Klap-in** [comment]
You have still have enough disk space?
The plugin download is about 50MB and unwrapped I guess it is using another time this disk space.

See for more clues at #194, #252 and #244
