### ISSUE TITLE
Dw2pdf plugin in combination with imagereference plugin

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [splitbrain/dokuwiki-plugin-dw2pdf#276]
Hi,

I'm using the imagereference plugin in combination with the dw2pdf plugin. When exporting the pdf file the links (```<imgref XY>```) to the pictures aren't interpreted as internal links.

(See also https://github.com/Klap-in/dokuwiki-plugin-imagereference/issues/29)

Best regards
Juergen

**Comment by Klap-in** [comment]
I have to fix it in the imagereference plugin.
