### ISSUE TITLE
DW2PDF failed to work on a SLES11 SP4

### ISSUE THREAD

**Issue by ebnerbenoit** [splitbrain/dokuwiki-plugin-dw2pdf#296]
I have a dokuwiki on a SLES11/SP4. When I try to create a PDF, I have this error in the error_log of apache:

`[Tue Sep 05 10:22:02 2017] [error] [client 153.89.62.77] PHP Parse error:  syntax error, unexpected T_CLASS, expecting T_STRING or T_VARIABLE or '$' in /srv/www/htdocs/doczsys/lib/plugins/dw2pdf/DokuPDF.class.php on line 52, referer: http://nrbnrx0005.nrb.be/doczsys/doku.php?id=zos:storage:stat`

I have a Apache 2.2.12 and PHP 5.3.17 on it:

`[Tue Sep 05 10:15:13 2017] [notice] Apache/2.2.12 (Linux/SUSE) PHP/5.3.17 configured -- resuming normal operations`

When I check the source code, the problem is noted here:

```
        // we're always UTF-8
        parent::__construct(
            array(
                'mode' => $mode,
                'format' => $format,
                'fontsize' => $fontsize,
                'ImageProcessorClass' => DokuImageProcessorDecorator::class,
            )
        );
```

On the ImageProcessorClass. 

I'm not good enough in PHP to correct this by myself :(.

**Comment by splitbrain** [comment]
Your PHP is too old. dw2pdf require PHP 5.6+
