### ISSUE TITLE
Parse error after upgrade.

### ISSUE THREAD

**Issue by GermanyBert** [splitbrain/dokuwiki-plugin-dw2pdf#302]
Getting the following error after upgrade.  Any fix for this?

Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/sportsterpedia/public_html/lib/plugins/dw2pdf/DokuPDF.class.php on line 52

**Comment by splitbrain** [comment]
your php is out of date

**Comment by GermanyBert** [comment]
Is there an earlier version I can download and install?
