### ISSUE TITLE
Export to pdf - Removing part of page

### ISSUE THREAD

**Issue by fsgonzaga** [splitbrain/dokuwiki-plugin-dw2pdf#303]
Hello,
I would like to know if there's a way of removing a section of my page, on the exported pdf version? I have created a nav bar with tabs that I would like to remove from my printed version.
 Thanks in advance!

Best Regards,
Felipe Gonzaga.

**Comment by Klap-in** [comment]
pdf export specific styling can be added using an additional style sheet.
Please see https://www.dokuwiki.org/plugin:dw2pdf#styles
