### ISSUE TITLE
Pages in Subnamespaces get same level as Pages in Namespace

### ISSUE THREAD

**Issue by Maahaax** [splitbrain/dokuwiki-plugin-dw2pdf#308]
Hallo everybody,

I want to create a book of my Howto-Pages in my wiki. The structure I have is the following:
**company:howto:**
This namespace contains a lot of pages, but has also a subnamespace:
**company:howto:sap:**
which again contains a lot of pages.
If I now create a PDF for the complete howto namespace I've thought, that every page being part of a subnamespace is found under its specific namespace. But the PDF contains every page with the same level of hierarchy, f.e.:

1. company:howto:howto1
2. company:howto:subnamespace:howto2
3. company:howto:howto2
4. company:howto:subnamespace:start
5. company:howto:howto3
6. company:howto:subnamespace:howto1
7. company:howto:subnamespace:howto3

You get the point. The result I would've expected is:

1. company:howto:howto1
2. company:howto:howto2
3. company:howto:howto3
4. company:howto:subnamespace:start
4.1. company:howto:subnamespace:howto1
4.2. company:howto:subnamespace:howto1
4.3. company:howto:subnamespace:howto3

Do you have any idea, how I can achieve this?

Beste regards!

**Comment by Klap-in** [comment]
What is your current url to start the export?
(please provide all the info so that others can reproduce your case, thanks.)

**Comment by Maahaax** [comment]
The URL I'm using is:
doku.php?id=gre:start&do=export_pdfns&book_ns=gre&book_title=GRE-Wiki
The following subnamespaces exists, each can have other namespaces.
![grafik](https://user-images.githubusercontent.com/8501991/33595881-0c6b23d0-d99a-11e7-88a2-e6ce83e33c64.png)

**Comment by Pantabo** [comment]
[issue_308.pdf](https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/files/1663961/issue_308.pdf)
Here is an example from our wiki with the same issue. The PDF bookmarks only includes the headlines of the sites. The namespaces get ignored otherwise it should look like:
+ EDV
  + Firefox
    + uBlock
Regards

**Comment by TomQv** [comment]
I have the same issue, Sub-namespaces are ignored in pdf, so the order of the pdf is useless.
Order-parameter is not helping.
Any workaround available in the meantime?

Wiki:
https://wikiqvx1.qvgps.de/doku.php?id=de:start
Pdf:
https://wikiqvx1.qvgps.de/doku.php?do=export_pdfns&book_ns=de&book_title=qvx1_test3&book_order=pagename

**Comment by TomQv** [comment]
I have the same issue. Sub-namespaces are placed on toplevel order making the pdf useless.
Any workaround available?

Wiki:
https://wikiqvx1.qvgps.de/doku.php?id=de:start

Pdf:
https://wikiqvx1.qvgps.de/doku.php?do=export_pdfns&book_ns=de&book_title=qvx1_test3&book_order=pagename

**Comment by TomQv** [comment]
Funktioniert jetzt, Reihenfolge stimmt. danke :)

Nur die allererste Seite, de:start, kommt als letztes im pdf.
Hast Du dazu eine Idee?
