### ISSUE TITLE
Images not showing up in PDF export

### ISSUE THREAD

**Issue by syphernl** [splitbrain/dokuwiki-plugin-dw2pdf#31]
When exporting a Dokuwiki page to PDF using dw2pdf the images are not added.

Specs:
- DokuWiki (2012-01-25a "Angua")
- Closed Wiki
- Group "@ALL" has no access rights
- Latest Version of dw2pdf (2012-05-20)
- userewrite is set to ".htaccess"
- Running on nginx + php5-fpm with rewrites in the nginx vhost config

Used markup:
`{{  :documentation:admin_level:clustman1.png }}`

Also tried a lot of other options, nolink, adding dimensions etc but none of which work

**Comment by YulongHe** [comment]
I have solve this problem. key word:"picture alpha channel" 

reference: https://www.cedric-meury.ch/2012/12/the-dw2pdf-dokuwiki-plugin-cannot-handle-rgba/
