### ISSUE TITLE
book_order = indexmenu

### ISSUE THREAD

**Issue by MoacirSchmidt** [splitbrain/dokuwiki-plugin-dw2pdf#310]
Hi, All

Thanks for your great plugin!

I'm using the indexmenu plugin to organize my wiki in a "table of contents". 

I would like to know if there is a way to "book order" the entire wiki using index sort order (indexmenu plugin)

**Comment by Klap-in** [comment]
Sorry, that is not available.
The sorting of the indexmenu plugin is custom for that plugin, and is not easy reusable.
Initiatives to refactor it and making it reusable are welcome.
