### ISSUE TITLE
Header and footer appear in cover page

### ISSUE THREAD

**Issue by librilex** [splitbrain/dokuwiki-plugin-dw2pdf#314]
When I add a cover page, the PDF cover page has the same header and footer as the following pages generated from dokuwiki articles. Am I missing a configuration parameter to surpress this behavior or add a cover page specific header and footer?

**Comment by Klap-in** [comment]
https://www.dokuwiki.org/plugin:dw2pdf:pdftemplate
Can you apply `header_first.html` and `footer_first.html` for separate header/footer at first page?

**Comment by Klap-in** [comment]
I assume this is working?

**Comment by librilex** [comment]
Sorry for my late response!
Yes, it is working. Thank you for the tip, it worked. I assumed `*_first.html` files were relevant for the first wiki page and not the first page of the book.
Now I just have to find out how not to enumerate the cover page (hence starting the first page after the cover page at number 1).

**Comment by Klap-in** [comment]
The manual of the library mPDF used by dw2pdf plugin, has more info about this.
I don't know if it only needs modifications of the template or more changes.

https://mpdf.github.io/

**Comment by pczekalski** [comment]
Actually, it solves the problem of the cover page (cover.html) but does not help on the back page (back.html) - back page still uses regular header/footer. How to remove it on the back page?
