### ISSUE TITLE
PHP 7.2 warning in MPDF code breaks export

### ISSUE THREAD

**Issue by daaain** [splitbrain/dokuwiki-plugin-dw2pdf#316]
I was unable to export (just got a redirect) which was due to a warning triggered by a line in MPDF code. For details see this issue: https://github.com/mpdf/mpdf/issues/562

Manually applying the code change fixed the issue for me and it was fixed in the library 19 days ago, please update the dependency when you have time!

**Comment by Klap-in** [comment]
Now mpdf 8 is used.
