### ISSUE TITLE
Startpage should be first on namespace-export

### ISSUE THREAD

**Issue by frank-w** [splitbrain/dokuwiki-plugin-dw2pdf#319]
Startpage (default "start") should be the first page when exporting a full Namespace

**Comment by frank-w** [comment]
Currently Pages are sorted alphabetically so startpage is at position "s". Basicly sorting should be done without the startpage and then insert startpage at position 0 :)

**Comment by dennisverspuij** [comment]
Addressed in [first commit](https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/pull/359/commits/f6242caab9748b269d645ffe651b922c93308899) of my PR.
I agree this is what users may expect in general, still others may actually like it as it is, so per haps it should be configurable, or e.g. as sort value pagename2?

**Comment by frank-w** [comment]
hi @dennisverspuij 

tried out your Patch, but my startpage is not moved to beginning...

i try to export this namespace

https://www.fw-web.de/dokuwiki/doku.php?id=en/bpi-r2/start

Startpage (start) is named like first header (BananaPi R2) and is Page 57 in the pdf

**Comment by dennisverspuij** [comment]
Hi @frank-w 
Did you add parameter book_order=pagename to your URL?

**Comment by dennisverspuij** [comment]
The patch does work correctly, please see this link:
[https://www.fw-web.de/dokuwiki/doku.php?do=export_pdfns&book_ns=en:bpi-r2&book_title=bananapi_r2&book_order=pagename](https://www.fw-web.de/dokuwiki/doku.php?do=export_pdfns&book_ns=en:bpi-r2&book_title=bananapi_r2&book_order=pagename)

**Comment by frank-w** [comment]
i have not put direct link...


~~PDFNS>en:bpi-r2|BananaPi-R2_EN_FW-WEB-Wiki~~

**Comment by dennisverspuij** [comment]
In the [docs](https://www.dokuwiki.org/plugin:dw2pdf#syntax) you'll find how to add the book_order parameter.

**Comment by frank-w** [comment]
thank you, works so far, any response that your patch can go into official sources?

**Comment by Klap-in** [comment]
This is implemented by #399
