### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by boogiewoo** [splitbrain/dokuwiki-plugin-dw2pdf#324]
got these message
`
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/public_html/wiki/lib/plugins/dw2pdf/DokuPDF.class.php on line 57`

there are two wikis on this server and on both the dw2pdf plugin didt'n work

**Comment by splitbrain** [comment]
your php is too old

**Comment by boogiewoo** [comment]
i see thanks!
