### ISSUE TITLE
Empty  checkboxes from <todo> plugin

### ISSUE THREAD

**Issue by surdinboris** [splitbrain/dokuwiki-plugin-dw2pdf#329]
Hi, all
Mentioned plugin on dokuwiki 2017-02-19e "Frusterick Manners, PHP 5.6.33,dw2pdf date 2018-01-10. 
Encountered an issue with checkboxes from todo plugin. All elements of checkbox were exported fine except status itself - all checkboxes are constantly empty.
Thanks!

**Comment by Klap-in** [comment]
Maybe there is some javascript action going on?

However, maybe the authors could add simplified html output for this plugin.
The plugin authors could use these instructions: https://www.dokuwiki.org/plugin:dw2pdf:exportsupport
