### ISSUE TITLE
Failed to load PDF document with {{upload}} tag

### ISSUE THREAD

**Issue by surdinboris** [splitbrain/dokuwiki-plugin-dw2pdf#330]
Hi, all 
Mentioned plugin on dokuwiki 2017-02-19e "Frusterick Manners, PHP 5.6.33, dw2pdf date 2018-01-10.
If an {{upload}} tag presented on target page,  in the middle of pdf generation process client page (url... &do=export_pdf)  eventually refreshes and  catches an error 'Failed to load PDF document', i guess due to still not finished pdf generation. Only page refresh with cache clearing is helpful for sucess pdf downloading.
 {{upload>@NS@:@PAGE@|OVERWRITE|RENAMEABLE}}
https://www.dokuwiki.org/plugin:upload

Thanks!

**Comment by Klap-in** [comment]
Please open a ticket at the tracker of the upload plugin. Its author can support the dw2pdf plugin by using the following instructions: https://www.dokuwiki.org/plugin:dw2pdf:exportsupport
It allows to not display this upload form, if html is outputted to the dw2pdf plugin.
