### ISSUE TITLE
Update mpdf library

### ISSUE THREAD

**Issue by gamma** [splitbrain/dokuwiki-plugin-dw2pdf#333]
A lot has happened since the library was updated in this plugin. It would be great to pull in the latest (7.0.3 as of now) release changes.

**Comment by Klap-in** [comment]
I hope that @micgro42 has the possibility to perform this update. A special point of attention is in the image decorator, which needs some modifications for DokuWiki.
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/issues/246#issuecomment-346011603

**Comment by micgro42** [comment]
This is "only" a micro update, so hopefully, it will be simple to apply. I will see if I can make the time.

What issues do you hope to have resolved with the new patch? I am aware of #316 (which is also a case of suboptimal server configuration), are there other issues with dw2pdf that an update of mpdf could resolve?

**Comment by gamma** [comment]
Specifically mpdf/mpdf#579 - it reduces memory consumption for very large CSS generated by DW. Using the i-netsoftware/siteexport plugin with dw2pdf I had to hack/patch a method in mpdf. But since they are in GitHub 'now' I was able to submit the PR.

**Comment by micgro42** [comment]
Ah, that might indeed be helpful! :+1:

**Comment by micgro42** [comment]
I opened a PR with the update. As far as I can tell, no adjustments to our DokuWiki code seem necessary.

Could you test it and see if it works for you?

**Comment by Klap-in** [comment]
@gamma mPDF 7.03 is available since #334 is merged.

Does it delivers the performance gain?

**Comment by gamma** [comment]
Sorry, I had no chance for a test yet ... will try soon.
