### ISSUE TITLE
custom cover page

### ISSUE THREAD

**Issue by annProg** [splitbrain/dokuwiki-plugin-dw2pdf#335]
use the template  cover.html  could generate a cover , but it's not flexible enough.

I hope to use a wiki page(only contain an image) to work as a cover. But the problem is the cover image can't  overspread whole page.Is there any way to let cover image use full page?

![abcd](https://user-images.githubusercontent.com/4145852/36678302-54497a56-1b4b-11e8-9a4a-2d3292adc714.jpg)

**Comment by moninformateur** [comment]
How did you achieve this?
