### ISSUE TITLE
 Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by KirillNaumkin** [splitbrain/dokuwiki-plugin-dw2pdf#336]
Each time I click "Export to PDF" I get an error page with the next content:

```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in \dokuwiki\lib\plugins\dw2pdf\vendor\mpdf\mpdf\src\Otl.php on line 5786
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in \dokuwiki\lib\plugins\dw2pdf\vendor\mpdf\mpdf\src\Otl.php on line 5786
```

If I press Back and click "Export to PDF" again - works just fine. It can be reproduced for any wiki-page.

  - Windows 10 Enterprise x64
  - IIS 10.0.14.393 x64 + [windows.php.net](http://windows.php.net/) (gd2 and mbstring are unlocked in php.ini).

**Comment by Klap-in** [comment]
Please could you retest with the last release of dw2pdf plugin? The libary used by the tool is updated, so I expect this is solved as well.
