### ISSUE TITLE
Not all images are exported

### ISSUE THREAD

**Issue by daumling** [splitbrain/dokuwiki-plugin-dw2pdf#337]
For some reason, the exported PDF contains only some of the images on the page. Please see https://doc.terrapinlogo.com/doku.php/logo:install_win. Using absolute namespaces does not work either. The images are PNGs.

If you need access to the server, please let me know.

[how_to_download_and_install_terrapin_logo_on_windows.pdf](https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/files/1783913/how_to_download_and_install_terrapin_logo_on_windows.pdf)

**Comment by daumling** [comment]
Hi Ruud,

thank you for the hint. Turns out that the gd module was installed for 
PHP 7.2, but Dokuwiki still ran with PHP 7.0. Works just fine now!

Thanks again, Michael

------ Originalnachricht ------
Von: "Ruud" <notifications@github.com>
An: "splitbrain/dokuwiki-plugin-dw2pdf" 
<dokuwiki-plugin-dw2pdf@noreply.github.com>
Cc: "Michael Daumling" <git@daumling.com>; "Author" 
<author@noreply.github.com>
Gesendet: 12.03.2018 09:48:41
Betreff: Re: [splitbrain/dokuwiki-plugin-dw2pdf] Not all images are 
exported (#337)

**Comment by Klap-in** [comment]
Please share some properties of your system. e.g. OS, webserver, versions. Thanks.

**Comment by daumling** [comment]
Klap-in, I am good. I used the wrong PHP version without the gd library installed.
