### ISSUE TITLE
dw2pdf after update to newest version not working

### ISSUE THREAD

**Issue by fdmgit** [splitbrain/dokuwiki-plugin-dw2pdf#340]
I've update the dw2pdf plugin using the extension manager to the news version. 
--> After the update I'm getting only a blank page. 

In the error-log I'm getting the following message:

[Wed Mar 28 18:07:45.339621 2018] [-:error] [pid 10522:tid 34722892800] [client xx.x.xxx.xx:62914] FastCGI: server "/var/run/hcgi/3699" stderr: PHP Fatal error:  Class 'Mpdf\\Image\\ImageProcessor' not found in ....../lib/plugins/dw2pdf/DokuImageProcessorDecorator.class.php on line 5, referer https://kb.perunis.ch/doku.php/start

The system is running PHP 7.0 und GD is enabled. 

I did a roll-back to the previous version of dw2pdf and everything works fine again.

**Comment by Klap-in** [comment]
Does FastCGI support less language features than apache?

Following lines are related:
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/976d2530cb77288b41606fd66f7ef08fdab08dbb/DokuImageProcessorDecorator.class.php#L5


https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/976d2530cb77288b41606fd66f7ef08fdab08dbb/vendor/mpdf/mpdf/src/Mpdf.php#L9

```php
use dokuwiki\plugin\dw2pdf\DokuImageProcessorDecorator as ImageProcessor;
```

**Comment by splitbrain** [comment]
no. fastcgi is just another way to access php from the web server. it's exactly the same language feature set. @fdmgit which php version are you running?

**Comment by splitbrain** [comment]
never mind, just saw its 7.0

**Comment by fdmgit** [comment]
@splitbrain 

Did some additional testing:

- I uninstalled the DW2PDF plugin using Extension Manager and then installed DW2PDF plugin (new version) again using the Extension Manager. ---> it works 

- if I uninstall the DW2PDF plugin manually and then install the new version of  DW2PDF plugin manually ---> it works

- If I use the Extension Manager to just update an installed DW2PDF version to the newest version the Extension Manager shows a 'successful update' message but the plugin is not working.

**Comment by Klap-in** [comment]
Could it be that deleted.files removes too much?
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/commit/fc682a6ef9069a163b7968d4fa91c8670144c0de

I tried a bit. I suspect that the line `vendor/mpdf/mpdf` in deleted.files removes something that is essential...

**Comment by Klap-in** [comment]
I have undo the deletion of the entire library in 5e2552ce9a5b06237b163f9bff6d8b491f1e9474

Could you check if update of library fixes this issue?

**Comment by Klap-in** [comment]
Probably fixed
