### ISSUE TITLE
Problem exporting with  Ditaa Plugin

### ISSUE THREAD

**Issue by helimech** [splitbrain/dokuwiki-plugin-dw2pdf#346]
Was working fine a few weeks ago but now trying to export any pages with a Ditaa diagram causes the pdf to take a minute or more to try and "print" and once it does the ditaa does not display just a red x

Both Plugins and Dokuwiki are updated to latest versions. (Ditaa using java renderer - java-8-openjdk-amd64)

Ditaa renders fine on screen. 

Not seeing anything in the standard logs, don't know if d2pdf has its own log?

![ditaa](https://user-images.githubusercontent.com/25013235/39612043-cb26be38-4f10-11e8-9871-49b18afd7812.png)

**Comment by cjohnsonuk** [comment]
I had this some time ago when trying to print JS created content.  There were quite a few posts but I can't remember the outcome.  Definitely think its related to it being JS created content

**Comment by Klap-in** [comment]
My first guess this is something that should be solved in the Ditaa plugin. So please create in its bug tracker a ticket to create awareness.

**Comment by Klap-in** [comment]
Some ways to retrieve more info from the dw2pdf plugin are explained at: https://www.dokuwiki.org/plugin:dw2pdf#how_to_collect_more_debug_info

Does it help you maybe?

**Comment by helimech** [comment]
Doh, close issue. It works fine locally (intranet site),just remote access is not working which means its most likely a NGINX config issue. 

Thanks for the suggestions though , appreciated.
