### ISSUE TITLE
Exporting pages without titles gives the filename ".pdf"

### ISSUE THREAD

**Issue by psy-q** [splitbrain/dokuwiki-plugin-dw2pdf#348]
It seems if a page has only content and no title (= heading), it is exported as ".pdf". I can open this on Linux but I'm not sure how other operating systems handle files with no name in front of the extension.

Could it perhaps default to the page ID + .pdf in such cases?

**Comment by ajc13** [comment]
Not sure of the protocol, but I am seeing this issue as well.  Duplicated me on Win10 in Chrome, FF and Edge.

**Comment by TimFFischer** [comment]
Unluckily, it's still there. On Windows a correct pdf reader is suggested, but has to be opened separately. Additionally, it's hard to see, whether e.g. the file "pdf (34)" or "pdf (35)" is my downloaded page "myFirstDokuWikiPage"

**Comment by Klap-in** [comment]
Fixed by #355
