### ISSUE TITLE
Parameter must be an array or an object that implements Countable in .../inc/changelog.php on line 226

### ISSUE THREAD

**Issue by jenolan** [splitbrain/dokuwiki-plugin-dw2pdf#349]
This is occurring on a new wiki as there is no media changelog yet, if the file is not there the @file read returns false which count then can not process.

Change
```php
    if ($flags & RECENTS_MEDIA_PAGES_MIXED) {
        $media_lines = @file($conf['media_changelog']);
        $media_lines_position = count($media_lines)-1;
    }
```
To
```php
    if ($flags & RECENTS_MEDIA_PAGES_MIXED AND file_exists($conf['media_changelog']) ) {
        $media_lines = @file($conf['media_changelog']);
        $media_lines_position = count($media_lines)-1;
    }
```

**Comment by Klap-in** [comment]
This sounds like something that needs to be solved in the DokuWiki source, while you have reported this now for a plugin. A report upstream is welcome!

**Comment by jenolan** [comment]
Yeah didn't realise ... should be closed
