### ISSUE TITLE
[REQ] Location of .less files in DW /conf

### ISSUE THREAD

**Issue by jnko** [splitbrain/dokuwiki-plugin-dw2pdf#351]
If possible it would be really nice if we could place modified *.less files or .css (for example pdf.less) in DokuWiki /conf directory instead of /lib/plugins/PLUGINNAME. 

This way these files would not be overwritten when updating the plugin.

**Comment by Klap-in** [comment]
Please see https://www.dokuwiki.org/plugin:dw2pdf:pdftemplate#style_sheets_loaded_by_dw2pdf for the css files loaded by the dw2pdf. 

If you like to set it for all pdf-template you can use: lib/plugins/dw2pdf/conf/style.local.css
If you like to set it per pdf-template, then make own pdf-template with a `style.css`. (or make a copy/rename pdf-template folder 'default´) ('default´ is overwritten on plugin updates).
