### ISSUE TITLE
Performance with DNS

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [splitbrain/dokuwiki-plugin-dw2pdf#352]
Hi,

when I create a PDF with the "normal" web-url ("http://appsrv03/wiki/...") it lasts approximately 3 minutes until the file is generated. The same call with the absolute server adress (e.g. "http://172.16.84.29/wiki/...") lasts only 10 - 20 seconds.
It seems that the DNS resolution deteriorates the performance

Can someone give me a hint to solve this?

Best regards
Juergen

**Comment by splitbrain** [comment]
Disable QR code generation. Also investigate why your server's DNS resolving is broken.
