### ISSUE TITLE
PDF auto-print

### ISSUE THREAD

**Issue by rclbrg** [splitbrain/dokuwiki-plugin-dw2pdf#354]
I suggest to add an optional javascript function to open the system print dialog after pdf export (Auto-print).
This can be achieved by adding to action.php in line 465:

`       $mpdf->SetJS('this.print();');`

It certainly makes sense to make this configurable.

**Comment by Klap-in** [comment]
We cannot add every detail. So I propose to not add this. Maybe we should think about having option to extend the settings of mpdf directly per pdf-template?
