### ISSUE TITLE
PHP 5.6 compatibility issue due to random_int()

### ISSUE THREAD

**Issue by rawIce** [splitbrain/dokuwiki-plugin-dw2pdf#356]
hello, 
in the plugin description [https://www.dokuwiki.org/plugin:dw2pdf](https://www.dokuwiki.org/plugin:dw2pdf) it says PHP 5.6 and newer are supported. 

We are running `PHP 5.6.36-0+deb8u1 (cli) (built: Jun 26 2018 17:31:29)` with DW2PDF version from 2018-04-23. 

While executing an export with images on the wiki page, the following error occurs: 
`[:error] [pid 28404] [client 10.107.10.132:63671] PHP Fatal error:  Call to undefined function Mpdf\\Image\\random_int() in /var/www/html/lib/plugins/dw2pdf/vendor/mpdf/mpdf/src/Image/ImageProcessor.php on line 505, referer: http://...`

_random_int()_ seems to be a PHP 7 function or seems to require some third party implementation [http://php.net/manual/de/function.random-int.php](http://php.net/manual/de/function.random-int.php)

Is there anything I am missing or is the current implementation regarding 5.6 support intended? 

Thanks!

**Comment by Klap-in** [comment]
It should be available..

the mpdf library has as requirement `paragonie/random_compat`
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/c0d3e52344be3259919d561a1112d147714ed1f7/vendor/mpdf/mpdf/composer.json#L41

in dw2pdf plugin this dependency is removed, because the dokuwiki itself has already this library available.
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/commit/7f027680141758e6badc1b25b4a5f0e18a8bb6cf

Which version of DokuWiki are you using?

**Comment by rawIce** [comment]
we are currently still running `Release 2015-08-10a "Detritus"`. However we are thinking of upgrading to up to date version.

**Comment by Klap-in** [comment]
That version misses indeed the random_compat library. So by upgrading DokuWiki you could solve this.

**Comment by rawIce** [comment]
Indeed upgrading our DokuWiki installation resolved that issue. However I would suggest to remove the _2015-08-10 "Detritus"_  compatibility flag in the plugin description then. 

Thanks for your afford and helping with that issue! 

In case anybody has to use this plugin on a Detritus build, there are only three lines in `/var/www/html/lib/plugins/dw2pdf/vendor/mpdf/mpdf/src/Image/ImageProcessor.php` utilizing `random_int()`. Due to the fact those lines only seem to handle temporary files, replacing `random_int()` with `rand()` works fine. However please be aware that generally speaking rand() and random_int() are two different things and are not interchangeable in a cryptographic and safety context.

**Comment by splitbrain** [comment]
@rawIce you can remove the compatibility flag yourself - it's a wiki ;-) Thanks for helping out.
