### ISSUE TITLE
Change Link Name from "Export Namespace xxx to File xx.pdf"

### ISSUE THREAD

**Issue by bernddausch** [splitbrain/dokuwiki-plugin-dw2pdf#362]
I use the link ~~PDFNS>Namespace|Filename~~ this was presented as 
"Export Namespace xxx to Fiel xx.pdf" can i change the Label in "Export to PDF"?

**Comment by Klap-in** [comment]
The title you set ("Filename" in your example), is filled in the translated string.

```
$lang['export_ns']         = 'Export namespace "%s:" to file %s.pdf';
```
Here, the first %s is replaced by the namespace and the second %s by the given title.
You can replace the translated string with your own one, see:
https://www.dokuwiki.org/localization#changing_some_localized_texts_and_strings_in_your_installation

When a string contains more placeholders you can swap the order in your localisation by using numbered placeholders of the form `%1$s` (`1$` is added), or for the second one: `%2$s`
