### ISSUE TITLE
Display pdf in new Tab

### ISSUE THREAD

**Issue by sandos187** [splitbrain/dokuwiki-plugin-dw2pdf#363]
Hi there,

is there a way to configure, that when ['output'] is set to 'browser', that the pdf is opened in a new tab or window (target _blank) instead of the same tab? That would be very helpful.
If not, is it possible to add such an option to the plugin?

Best regards

sandos

**Comment by Klap-in** [comment]
No idea. Because for most people the current behavior seems logic, I have not yet the intent to change it. However, if more people support this, a pull request is welcome.
