### ISSUE TITLE
Fatal error: Call to undefined function css_styleini() in /usr/local/nginx/html/dokuwiki/lib/plugins/dw2pdf/action.php on line 680

### ISSUE THREAD

**Issue by wuzhihu** [splitbrain/dokuwiki-plugin-dw2pdf#367]
Fatal error: Call to undefined function css_styleini() in /usr/local/nginx/html/dokuwiki/lib/plugins/dw2pdf/action.php on line 680

**Comment by Klap-in** [comment]
Do you have the latest version of the dw2pdf plugin?

**Comment by wuzhihu** [comment]
Thank you, downloaded in the following connection


URL：https://www.dokuwiki.org/plugin:dw2pdf?s[]=dw2pdf



------------------ 原始邮件 ------------------
发件人: "Gerrit Uitslag"<notifications@github.com>;
发送时间: 2018年12月21日(星期五) 晚上11:38
收件人: "splitbrain/dokuwiki-plugin-dw2pdf"<dokuwiki-plugin-dw2pdf@noreply.github.com>;
抄送: "绝情浪子"<987704751@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [splitbrain/dokuwiki-plugin-dw2pdf] Fatal error: Call toundefined function css_styleini() in/usr/local/nginx/html/dokuwiki/lib/plugins/dw2pdf/action.php on line 680(#367)




Do you have the latest version of the dw2pdf plugin?

**Comment by Klap-in** [comment]
Closed, as I assume it is working now.
