### ISSUE TITLE
Table header grey background not printed/exported on pdf

### ISSUE THREAD

**Issue by dobunzli** [splitbrain/dokuwiki-plugin-dw2pdf#373]
Hello,
Using 2018-04-22b "Greebo" and latest dw2pdf plugin (20.03.2019)

I created a table with headers in doku wiki. The headers of the table are nicely identified because they have a grey background.

When I export the wiki to pdf using dw2pdf, the grey background is not present on the pdf.

See attached pictures.
![Header_DokuWiki](https://user-images.githubusercontent.com/28629186/56089964-19f5ed00-5e9b-11e9-9962-8c70ebc6d332.png)
![Header_PDF](https://user-images.githubusercontent.com/28629186/56089965-1c584700-5e9b-11e9-8b0f-2dfe26de7882.png)

Thanks for suggestions.

**Comment by Klap-in** [comment]
The pdf export uses default the print style sheets. (That is what you see if you try the print preview in your browser)

You can introduce your own styling for the pdf export with the info at: https://www.dokuwiki.org/plugin:dw2pdf:pdftemplate

**Comment by dobunzli** [comment]
Ok thanks for your answer. As I am not familiar with css I have opened a thread [in the forum](https://forum.dokuwiki.org/thread/16909)
