### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by kadsystems** [splitbrain/dokuwiki-plugin-dw2pdf#379]
When I click the Export to Pdf button, I get an HTTP ERROR 500. What could be the problem, where do I start to find a solution?

**Comment by hugorn** [comment]
Same error here.

**Comment by Klap-in** [comment]
Please have a look in the logs. The 500 error indicate that the webserver was broken in certain way, but does not explain why and where. I need the this info to know at least where the webserver finishes.

**Comment by Klap-in** [comment]
log message are missing.
