### ISSUE TITLE
any chance to support  flowcharts like a2s?

### ISSUE THREAD

**Issue by zeerd** [splitbrain/dokuwiki-plugin-dw2pdf#381]
Hello!

I am using those two plugins to make a rich info web page.
But I find dw2pdf could not use the svg generated by flowchart , but a2s is ok.

Refer:
https://www.dokuwiki.org/plugin:a2s
https://www.dokuwiki.org/plugin:flowcharts

**Comment by splitbrain** [comment]
flowchart uses the mairmaid Javascript to render charts client side. dw2pdf can not run Javascript.
