### ISSUE TITLE
Automate creation of PDF's with DW2PDF

### ISSUE THREAD

**Issue by TrapSpace** [splitbrain/dokuwiki-plugin-dw2pdf#390]
Dear @splitbrain , 

First of all thank you for all you do for the DW community, needs to be said! 

I currently have a private DW running and installed the DW2PDF plugin and it works great.  I was wondering if you could give me some guidance as to how I could automate the creation of PDFs with this plugin. 

What I am looking to is build a cronjob that uses this plugin and maybe curl to download PDF's of my DW periodically. If you could provide me with some guidance or ideas would be awesome! 

Thank you very much

Dino

**Comment by splitbrain** [comment]
Well if you can use curl, it should be trivial to setup a cron job to fetch the PDFs you want. If you have trouble setting it up, I recommend asking in the forums (with some specific questions).
