### ISSUE TITLE
[plugin:a2s]For arrowheads of pictures drawn by a2s

### ISSUE THREAD

**Issue by zeerd** [splitbrain/dokuwiki-plugin-dw2pdf#396]
https://www.dokuwiki.org/plugin:a2s

The author of a2s said:
`
When I export to pdf with dw2pdf, the arrowheads on line are not drawn, and alignment is not respected. Can you/I do something about that ?
`
`
No. As of 2017/07/27, unless you are the a developer of dw2pdf or mpdf, its PDF library, there is nothing to do. Sorry. 
`

So, any chance to know , is a dw2dpf issue? or a mpdf issue? Where could I get more help for this?

**Comment by Klap-in** [comment]
To know what is going before the content is given to mpdf-library, you can also output the html, just before it given to the mpdf library:
https://www.dokuwiki.org/plugin:dw2pdf#how_to_collect_more_debug_info

Further, there is some guidance for plugin support in dw2pdf, please have a look at 
https://www.dokuwiki.org/plugin:dw2pdf:exportsupport#use_custom_placeholders_in_html_templates for if extra means are needed.

**Comment by zeerd** [comment]
Thanks.

I did this test again. For a page like:

`
# Testing

<a2s>
--->
</a2s>

[[http://x.x.x.x/doku/doku.php?id=test&do=export_pdf&debughtml=html]]
`

It looks like below at the wiki page:

![ah1](https://user-images.githubusercontent.com/390170/79821943-97afdb00-83c2-11ea-8b38-d3f677fb30fe.png)

And it looks like below at the debughtml:

![ah2](https://user-images.githubusercontent.com/390170/79821967-a8605100-83c2-11ea-97cb-3f63a82b173c.png)

So, means I need to go mpdf for more helping?

**Comment by zeerd** [comment]
OK, I found it.

mPDF said, no marker supported.

https://mpdf.github.io/what-else-can-i-do/images.html#not-supported

*Sigh*.

**Comment by Klap-in** [comment]
Thanks for the details. What is the html itself? Could you post a copy of it here as well?

**Comment by zeerd** [comment]
Yes, sure. The html is here.

[a2s.txt](https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/files/4508966/a2s.txt)
