### ISSUE TITLE
Missing a line between the Content and the Footnotes

### ISSUE THREAD

**Issue by zeerd** [splitbrain/dokuwiki-plugin-dw2pdf#398]
Hello!

There is a line, which means `<hr/>` between the content and the footnote on the wiki page. 
But missing on the PDF.

For example: 

```
# Testing

Footnotes((123))

[[http://x.x.x.x/doku/doku.php?id=test&do=export_pdf&debughtml=html]]
```

The the html file 's here:

[Footnotes.txt](https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/files/4528121/Footnotes.txt)

**Comment by Klap-in** [comment]
Thanks for the example. However, I do not see a `<hr/>` in the provided example. That would explain why it is not shown? Also if I check that example in a browser, I do not see a horizontal line.

For this export to pdf, the simple version of the print view is used. This strips a lot of css, including the css of the footnotes.

In dokuwiki the following style is used. 
```
.dokuwiki div.footnotes {
    border-top: 1px solid #ccc;
}
```
You can add it to the `style.css` of your pdf-template. (make a copy, the default pdf-template is overwritten on update). Or you can also use `lib/plugins/dw2pdf/conf/style.local.css`.
