### ISSUE TITLE
[tablecalc plugin] calculated table values not exported

### ISSUE THREAD

**Issue by wexi79** [splitbrain/dokuwiki-plugin-dw2pdf#40]
When using the tablecalc plugin to calculate values for table cells, the cells are empty in the exported pdf.

**Comment by Klap-in** [comment]
This plugin uses, so far I understand, javascript to calculate the values. dw2pdf plugin doesn't evaluate javascript on export. 

This means in the tablecalc plugin a kind of workaround should be added to add support for this.
