### ISSUE TITLE
Fontawesome icons do not appear in PDF

### ISSUE THREAD

**Issue by fama** [splitbrain/dokuwiki-plugin-dw2pdf#402]
Installed the Icons plugin:
https://www.dokuwiki.org/%3Aplugin%3Aicons
http://www.lotar.altervista.org/wiki/wiki/plugin/icons

The icons display correctly on the page, however they do not apper in the PDF.

I already modified the `plugin»dw2pdf»usestyles` and added `fontawesome,fa`, yet the icons do not print.

Can you please help.

**Comment by Klap-in** [comment]
dw2pdf plugin uses mpdf library. Fonts that are not default included in mpdf has to be added to the mpdf by the user of mpdf. At the moment dw2pdf has not a feature to add this to mpdf.
With help of tutorials of mpdf you could add the fonts yourself in https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/master/DokuPDF.class.php. Ensure to make an backup, as this file is typically overwritten on plugin update.
Including extended font support (which configurable by wiki admin) in dw2pdf needs probably more work.

**Comment by Klap-in** [comment]
Example of configuration of fontawesome font: https://stackoverflow.com/a/58702825/1043588

Let's continue the discussion in #445.
