### ISSUE TITLE
Solved: Table vertical cell alignment differs from DokuWiki

### ISSUE THREAD

**Issue by bomhard** [splitbrain/dokuwiki-plugin-dw2pdf#404]
Great Plugin, thanks a lot. But we found one issue:

Tables with multiple lines are rendered with vertical-top-alignment which makes sense in most cases. In the pdfs however vertical alignment is centered which can be really more than a cosmetic flaw with larger multi-line tables.

Best
NIkolaus

**Comment by Klap-in** [comment]
The pdf creation is performed by the mpdf library. Unfortunately the library doesn't support all details of css. So it could be that alignment is not support in the way you need. e.g. sometimes inline css solves it. The plugin has some option to observe which html and css is going into it. And in the manual you have some explaination e.g. https://mpdf.github.io/css-stylesheets/supported-css.html

**Comment by bomhard** [comment]
Thanks a lot. Creating DWDIR/lib/plugins/dw2pdf/conf/style.local.css with:

``table {
   vertical-align: top;
}
``

solved the issue. Should be part of the default style.css to match rendering.
