### ISSUE TITLE
Impossible to download from repository

### ISSUE THREAD

**Issue by OnesimeP** [splitbrain/dokuwiki-plugin-dw2pdf#406]
Hi,

I get this message "Impossible de télécharger le fichier : https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master" when I tried to install the DW2PDF Plugin (on my http://carnet-terrain-electronique.onesi.me/ site).

Is there an issue?

**Comment by PresGas** [comment]
Hello! I also got this issue today, but then tried the upgrade again and it just worked. I wonder if there is just intermittency and not "quite" a problem? Did you end up being able to upgrade it?

**Comment by Klap-in** [comment]
The download of this plugin is relatively large. That might give sometimes issues.
