### ISSUE TITLE
Including table of contents create corrupt pdf file

### ISSUE THREAD

**Issue by geiger108** [splitbrain/dokuwiki-plugin-dw2pdf#414]
Hello, I'm working with dokuwiki version 2020-07-29 "Hogfather" on PHP 7.3 an the latest dw2pdf version (2020-08-20).

If you want to include a table of contents, no matter which option you choose, it creates a corrupt pdf file when using php 7.x. If you use php 5.6 the pdf creation, including a toc, is successfull.

I've analyzed the corrupt pdf file. It sais, that the "end of file marker" is missing.

Would love a quick & dirty fix until update is released, if anyone could help :-)

**Comment by Klap-in** [comment]
How do you add the Table of content? With which url parameter or syntax?
So if you could add a recipe for reproducing your case it would be helpful.
