### ISSUE TITLE
Selection caught, forced to POST

### ISSUE THREAD

**Issue by JeremyOWO** [splitbrain/dokuwiki-plugin-dw2pdf#418]
Hello,

We encountered a problem with using of selection.

When we use "selection" with Bookcreator, all is ok because Book creator use POST method to send selection and DW2PDF get selection with $INPUT->post->str

But in our case we developped a plugin using DW2PDF but with GET method to send selection.

So my question is:  Why not using $INPUT->str instead of $INPUT->post->str ? This will be more generic !

I'm creating a Pull Request for this.

Best Regards

**Comment by JeremyOWO** [comment]
Pull request Created: [Pull Request](https://github.com/JeremyOWO/dokuwiki-plugin-dw2pdf/pull/1)

**Comment by Klap-in** [comment]
GET-requests have a limitation in the length of the request. Therefore, for the bookcreator a POST-request is needed. Why do you need a GET-request? A POST-request would you allow bigger requests...

**Comment by JeremyOWO** [comment]
Yes the POST-request is the best method. 

But this modification will authorize a biggest choice for the method and not impact the working with POST-request.
We could change our method and so use POST but I think this pull request is interesting for some others developments needs.

**Comment by JeremyOWO** [comment]
UP,

Do you you understand the request ?

Thanks

**Comment by Klap-in** [comment]
Yes, I’m maybe not enough in the details to quick decide on this.

@splitbrain @micgro42 what is your opinion on switching to GET instead of POST?

**Comment by micgro42** [comment]
Ugh, this method is a mess.

I do not know the method good enough to have an opinion on the issue of the request size.

Setting that aside and reasoning from first principles, then this request doesn't seem to change the server state (caching doesn't really count) and so it should be fine to allow a GET request as well.
This will have the consequence that such a URL could be linkable. But I guess it is up to @JeremyOWO and their customers to figure out whether that is actually a good idea for their use case.

**Comment by Klap-in** [comment]
The `selection` parameter is filled by the Bookcreator plugin with strings of all the pages that should be added to a book. The bookcreator needs to submit a POST request to circumvent the size constraint of the GET request. 
@JeremyOWO request a change on the receiving side of the request.

The function sendPDFFile exits the request by sending the pdf to the browser.

So far as I know there where no other uses of this parameter before.

**Comment by Klap-in** [comment]
@micgro42 thanks for your reaction.
