### ISSUE TITLE
[box plugin] bad drawn boxes

### ISSUE THREAD

**Issue by Theasker** [splitbrain/dokuwiki-plugin-dw2pdf#42]
the plugin don't work with the box plugin

http://daw.xtrweb.com/dokuwiki/doku.php/wiki:box

when I exported to pdf the page ...

http://min.us/lbvEQCRShCqOhh

thanks in advance and sorry for the inconvenience

**Comment by Klap-in** [comment]
Provided links are broken.

Own test works fine for me.
Please provide a new test case. Thanks.
