### ISSUE TITLE
Only a white site is shown

### ISSUE THREAD

**Issue by reibach** [splitbrain/dokuwiki-plugin-dw2pdf#421]
Hello, 

System is a Debian Buster,  ii  dokuwiki       0.0.20180422.a-2 all          standards compliant simple to use wiki

[Thu Jan 21 15:00:43.307861 2021] [php7:error] [pid 16518] [client 0.0.0.0:63640] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function dokuwiki\\StyleUtils::cssStyleini(), 0 passed in /var/lib/dokuwiki/lib/plugins/dw2pdf/action.php on line 783 and at least 1 expected in /usr/share/dokuwiki/inc/StyleUtils.php:19\nStack trace:\n#0 /var/lib/dokuwiki/lib/plugins/dw2pdf/action.php(783): dokuwiki\\StyleUtils->cssStyleini()\n#1 /var/lib/dokuwiki/lib/plugins/dw2pdf/action.php(465): action_plugin_dw2pdf->load_css()\n#2 /var/lib/dokuwiki/lib/plugins/dw2pdf/action.php(98): action_plugin_dw2pdf->generatePDF('/var/lib/dokuwi...', Object(Doku_Event))\n#3 /usr/share/dokuwiki/inc/events.php(229): action_plugin_dw2pdf->convert(Object(Doku_Event), Array)\n#4 /usr/share/dokuwiki/inc/events.php(70): Doku_Event_Handler->process_event(Object(Doku_Event), 'BEFORE')\n#5 /usr/share/dokuwiki/inc/ActionRouter.php(80): Doku_Event->advise_before()\n#6 /usr/share/dokuwiki/inc/ActionRouter.php(48): dokuwiki\\ActionRouter->setupAction('export_pdf')\n#7 /usr/share/dokuwiki/inc/ActionRouter.php(60): dokuwiki\\ActionRouter->__cons in /usr/share/dokuwiki/inc/StyleUtils.php on line 19, referer: http://wiki/doku.php

**Comment by Klap-in** [comment]
Ah, I had clean up some code, but probably for older version this variable was still needed. I thinks this fix should solve your situation.

**Comment by reibach** [comment]
Thanks a lot, after the update, everything works fine!
