### ISSUE TITLE
Support for list-style

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [splitbrain/dokuwiki-plugin-dw2pdf#428]
Hi,

apparently the CSS parameters to "list-style" (‘list-style-type’, ‘list-style-position’, ‘list-style-image’) are not transferred. The debug mode (`&debughtml=html`) brings the correct display in the browser, but the PDF file itself is not affected.

Regards
Juergen

**Comment by Klap-in** [comment]
Mpdf provides unfortunately support for a limited set css features. Please check its manual for if this one is included.

**Comment by Juergen-aus-Zuendorf** [comment]
Yes, I've checked it:
see
![2021-03-09 07_34_21-Supported CSS – CSS   Stylesheets – mPDF Manual](https://user-images.githubusercontent.com/1800472/110428665-f305bd00-80a9-11eb-8fb5-d704759e464f.png)
 https://mpdf.github.io/css-stylesheets/supported-css.html

**Comment by Juergen-aus-Zuendorf** [comment]
Ok, thank you!

For simplicity here you can find some data of the following snippet:
```
unsortiert:
  * Zeile 1
  * Zeile 2

sortiert:
  - Zeile 1
  - Zeile 2
```
My template contains the following definition:
```
ul {
  list-style-type: '-';
}
```

The result as PDF is this:
[spielplatz.pdf](https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/files/6116768/spielplatz.pdf)

The debugging mode correctly outputs this HTML content:
```
<div class="level1">
<p>
unsortiert:
</p>
<ul>
<li class="level1"><div class="li"> Zeile 1</div>
</li>
<li class="level1"><div class="li"> Zeile 2</div>
</li>
</ul>
<p>
sortiert:
</p>
<ol>
<li class="level1"><div class="li"> Zeile 1</div>
</li>
<li class="level1"><div class="li"> Zeile 2</div>
</li>
</ol>
```

Regards
Juergen

**Comment by Klap-in** [comment]
In default hml/css a string would be an option: `  list-style-type: '-';` (https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type). But mpdf is bit more limited, so maybe just a string is not supported. Mpdf manual shows also option of using unicode. Could you try that as well? see example below.

I haven't tested yet further.

The help writes:
> 
> 1 | A | a | I | i | disc | circle | square | decimal | lower-roman | upper-roman | lower-latin | upper-latin | lower-alpha | upper-alpha | none
> 
> arabic-indic | bengali | cambodian | cjk-decimal | devanagari | gujarati | gurmukhi | hebrew |kannada | khmer | lao | malayalam | oriya | persian | telugu | thai | urdu | tamil
> 
> “1” - decimal
> 
> “A” = upper-latin
> 
> “a” = lower-latin
> 
> “I” = upper-roman
> 
> “i” = lower-roman
> 
> Custom list-style-type is recognised e.g.: `U+263Argb(255,0,0);`
> 
> where `U+263A` is the Unicode HEX value of the character you want for the bullet
> the character MUST be included in the font used for that list item
> `rgb()` bit is optional

I interpret that as:
```
  list-style-type: '1';
  list-style-type: 'A'; etc
  list-style-type: 'disc'; etc

The last line suggests this, U+002D is for dash, if I looked it up correctly.
  list-style-type: 'U+002D';

Or if that rgb should be used(seems optional):
  list-style-type: 'U+002Drgb(255,0,0)';
```

**Comment by Klap-in** [comment]
A quick look in the source code suggests just a string is probably not supported (it is not easy to read, so I might have miss something).

So please try the unicode approach.

**Comment by Juergen-aus-Zuendorf** [comment]
Yes, both unicode examples work fine

**Comment by Klap-in** [comment]
This is fixed?

**Comment by Juergen-aus-Zuendorf** [comment]
For me, it's ok, thank you
