### ISSUE TITLE
[graphviz plugin]not pdf output

### ISSUE THREAD

**Issue by sacl** [splitbrain/dokuwiki-plugin-dw2pdf#43]
Hi everybody ...

OS
Wheezy 7.0 - Debian 3.2.35-2 x86_64 GNU/Linux
dokuwiki Version: 0.0.20120125b-2
graphviz 2.26.3-12

PLUGINS
dw2pdf - 2012-05-20
graphviz  2010-11-24

PROBLEM
1) Graphviz works excellent.
2) Dw2pdf works excellent.
3) when exporting to PDF, so good even images.
4) But the graphics generated by graphviz ... NOT.
5) I made with colored and colorless. Just are not included in the PDF.

CODE EXAMPLE
<graphviz>
Digraph R
{
/\* Configuración general*/
rotate="90";
size="6,10";
bgcolor=transparent;

/\* Configuración nodos */
Reclamo [color="skyblue",style=filled];
Contener [shape=box];
Solucionado [shape=diamond, label="¿Solucionado?"];
Registrar [shape=box];
Evaluar [shape=box, label="Evaluar Méritos, Investigar"];
Valido [shape=diamond, label="¿Proceso Válido?"];
Informe [shape=box, label="Generar informe Técnico"];
Responder [shape=box, label="Responder al Paciente o Médico"];
Archivar [shape=box];
Fin [color="skyblue",style=filled];

SiSolucion [shape=circle,label="Sí",height=.4,fixedsize=true,color="green",style=filled];
NoSolucion [shape=circle,label="No",height=.4,fixedsize=true,color="red",style=filled];
SiValido [shape=circle,label="Sí",height=.4,fixedsize=true,color="green",style=filled];
NoValido [shape=circle,label="No",height=.4,fixedsize=true,color="red",style=filled];

/\* Código */
Reclamo -> Contener -> Solucionado;
Solucionado -> NoSolucion -> Registrar -> Evaluar;
Evaluar -> Valido -> SiValido -> Informe;
Informe -> Responder -> Archivar;
Archivar -> Fin;
Solucionado -> SiSolucion -> Fin;
Valido -> NoValido -> Responder;
}
</graphviz>

In advance, thanks for any help.
Sergio from CHILE

**Comment by Klap-in** [comment]
Some dw2pdf specific work in graphviz is done in this PR https://github.com/splitbrain/dokuwiki-plugin-graphviz/pull/14

Solution is based at creating file on the server which is included in the created pdf.

**Comment by Klap-in** [comment]
With current understanding this issue has to be solved by the graphviz plugin.
