### ISSUE TITLE
Option to disable header, footer and from code-block

### ISSUE THREAD

**Issue by WidgetMidget** [splitbrain/dokuwiki-plugin-dw2pdf#434]
I don't personally mind the header that much, but I dislike the footer simply because it includes a link. Likewise, the code-block that the QR-code is rendered in is disliked for the same reason.

![image](https://user-images.githubusercontent.com/75787425/116389889-c22a4480-a81d-11eb-8803-a80a14dab0d5.png)

![image](https://user-images.githubusercontent.com/75787425/116389901-c5253500-a81d-11eb-8c9d-b63c135ff682.png)

While these are _perhaps_, nice features to have if the wiki is public. An internal or private wiki won't really benefit from this and if I am going to be sharing a PDF anyway, I don't want it to include information that is pointless in regards to the actual contents. For example, for work I could export a page and hand it to an end-user, why would they ever have need for such confusing links and wiki titles if they can never reach it?

Thus, I think it ought to be considered to add individual switches for the header, footer and from-code-block thing or whatever you want to call that. Personally, I also think a secondary switch for the footer to remove the wiki link would be nice, as aside from that, I wouldn't mind the footer.

**Comment by splitbrain** [comment]
All of these can be removed or adjusted through the template mechanism. And since this is work context you probably want your own CI anyway.

**Comment by Klap-in** [comment]
On the wiki/documentation page of this plugin https://www.dokuwiki.org/plugin:dw2pdf, you can also find an HowTo about the templates. Please see https://www.dokuwiki.org/plugin:dw2pdf:pdftemplate

Please do not change the 'default' template, but make a copy and include in the copy your changes. Next, in the configuration settings you tell that your own template should be used for exports.
