### ISSUE TITLE
conflicts with plugin autotooltip

### ISSUE THREAD

**Issue by NikolausMB** [splitbrain/dokuwiki-plugin-dw2pdf#437]
tooltips created with autotooltip are written by dw2pdf to the pdf output.

**Comment by Klap-in** [comment]
Please report this in the issuetracker of this plugin. 

That plugin can do two things: 
- just suppress the added html by some hiding with css. 
- Or, use `if(is_a($renderer,'renderer_plugin_dw2pdf')){` to return simpler html which can be included in the pdf. See further  https://www.dokuwiki.org/plugin:dw2pdf:exportsupport
