### ISSUE TITLE
Feature request: Exclude namespaces

### ISSUE THREAD

**Issue by wekev** [splitbrain/dokuwiki-plugin-dw2pdf#449]
First at all, thanks for that Plugin!

Could you please add an exclude namespace feature, because I would like to export our whole DokuWiki into a PDF but don't want to include specific namespaces like 'playground' and I don't know all ids in that namespace.

My solution for that is:
```
// exclude namespaces
$excludesns = $INPUT->arr('excludesns');
if (!empty($excludesns)) {
    $result = array_filter($result, function ($item) use ($excludesns) {
        $namespace = substr($item['id'], 0, strrpos($item['id'], ':'));
        return array_search($namespace, $excludesns) === false;
    });
}
```
With the parameter(s) excludesns[] I'm now able to ignore all ids which starts with the defined namespace.

Small gap: This solution only excludes the exact namespace and don't remove sub-namespaces.
Maybe you will find a better solution or add this to your code?

Kevin

**Comment by Klap-in** [comment]
Is this not already available via the namespace export, initiated by the `do=export_pdfns` 

see also https://www.dokuwiki.org/plugin:dw2pdf:configuration#initiate_export_only_via_url-parameters , `&excludes[]=<namespaceid>`.

For a link in your wiki article 
https://www.dokuwiki.org/plugin:dw2pdf#syntax

**Comment by wekev** [comment]
Dear Klap-in, thanks for the fast reply!

I know these links, but I can't find there a solution. I will describe my situation:
We have one page in the root namespace :start and 10 namespaces :ns1 to :ns10 with different pages.
Additionaly we use a namespache :playground where the team got the right to create pages and content for testing. 
Nevertheless we have the namespace :wiki which contains several pages with help.

Now we would like to create a PDF-File which contains the root-page and the complete namspaces ns1 to ns10.

As I understand the documenttation I'm able to export a single namespace or the root with all the sub namespaces and could exclude specific pages, but I don't know all pages in the namespace playground. Therefore I'm not able to exclude all pages in that namespace.

With the extended excludesns-parameter and the code above I could generate the following link to export the whole wiki without all pages in the excluded namespaces:
dokuwiki/start?do=export_pdfns&book_ns=&book_title=Interne%20IT-Doku&excludesns[]=playground&excludesns[]=wiki
This works fine.

Did I misunderstand the doc and is there already a solution I didn' see?

**Comment by Klap-in** [comment]
Ah, I see, I’m sorry. I have improved the documentation directly, because I read it differently, but you are completely right.

Your solution looks as a fine start, a bit more practical matching is possible.
Checking if a namespaces has some overlap can be done with the substr() function.
An example for some inspiration:
https://codesearch.dokuwiki.org/xref/plugin/changes/syntax.php#360

The provided namespaces in excludesns should not have a `:` on the start or end.

A pull request is welcome.

**Comment by wekev** [comment]
Yes, the documentation is better now. 
By the way, you could extend the book_ns parameter description like this:
book_ns=<namespace> – (required) Exported namespace  (leave namespace empty for whole wiki)

I include the substr function, it solve my problem with sub namespaces, thanks!

Here my tested solution:

```
            // exclude namespaces (no : at start or end of namespace!)
            $excludesns = $INPUT->arr('excludesns');
            if (!empty($excludesns)) {
                $result = array_filter($result, function ($item) use ($excludesns) {
                    foreach ($excludesns as $ns) {
                        if ((strpos($item['id'], $ns . ':') === 0)) return false;
                    }
                    return true;
                });
            }
```
And you are right, the namespaces in excludesns should not have a ```:``` at start or end.

I would be happy if the code could be adopted to a future release ;)

**Comment by Klap-in** [comment]
You can now use this url parameter. 

Docs are updated:
`excludesns[]=<ns:ns> `– (optional) Full namespace id (no : before/after) to be excluded from export. Repeat the parameter to exclude multiple namespaces.
