### ISSUE TITLE
Incompatibility with latest Igor RC2 version of Wiki

### ISSUE THREAD

**Issue by zlobniyshurik** [splitbrain/dokuwiki-plugin-dw2pdf#457]
Can not enter to **Admin Panel -> Wiki Settings**. 
I got:

```

dokuwiki\Exception\FatalException: Declaration of renderer_plugin_dw2pdf::header($text, $level, $pos) must be compatible with Doku_Renderer_xhtml::header($text, $level, $pos, $returnonly = false)

An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the dw2pdf plugin.

More info has been written to the DokuWiki error log.
```
P.S. PHP 8.0

**Comment by Klap-in** [comment]
Could you try Reinstall the dw2pdf plugin.
I made a change (https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/commit/ba7b42ad77b34921ad522e53ffb42a8b757889d8). By reinstalling you can test it.

Please confirm if it is working.

**Comment by zlobniyshurik** [comment]
At least,  I can enter to Wiki Settings now.
Thank you very much!
