### ISSUE TITLE
Heredoc export problem inside html tag

### ISSUE THREAD

**Issue by Stikus** [splitbrain/dokuwiki-plugin-dw2pdf#458]
- Here is my page:

![image](https://user-images.githubusercontent.com/41360525/177590144-c8f56e00-d6b6-4e08-82ba-f31cf452845c.png)

- Here is its code:

```
<file>
cat <<'EOF' |  sed 's/l/e/g'
Hello
World
EOF
</file>

<code bash>cat <<'EOF' |  sed 's/l/e/g'
Hello
World
EOF</code>

<html><pre>cat <<'EOF' |  sed 's/l/e/g'
Hello
World
EOF</pre></html>
```

- And here is export result:

![image](https://user-images.githubusercontent.com/41360525/177590280-8137e8bf-a2c5-49df-8b65-8a657ed12340.png)

If I remove `<pre>` tag result will still be broken:

- Page:
 
![image](https://user-images.githubusercontent.com/41360525/177589674-e825decb-d10b-467a-b233-52d7e3835765.png)

- Code:
```
<file>
cat <<'EOF' |  sed 's/l/e/g'
Hello
World
EOF
</file>

<code bash>cat <<'EOF' |  sed 's/l/e/g'
Hello
World
EOF</code>

<html>cat <<'EOF' |  sed 's/l/e/g'
Hello
World
EOF</html>
```
- Result:

![image](https://user-images.githubusercontent.com/41360525/177589826-290fd077-4dd5-4087-b421-1b56d82eb5e1.png)

But if I remove  `<html>` tag completely everything working again:

- Page:
![image](https://user-images.githubusercontent.com/41360525/177590869-4ad06ae2-f5ba-4b4d-b35d-d1c8672d3c9b.png)

- Code:
```
<file>
cat <<'EOF' |  sed 's/l/e/g'
Hello
World
EOF
</file>

<code bash>cat <<'EOF' |  sed 's/l/e/g'
Hello
World
EOF</code>

cat <<'EOF' |  sed 's/l/e/g'
Hello
World
EOF
```
- Result:
![image](https://user-images.githubusercontent.com/41360525/177590930-102f4063-1e2a-47a0-85bb-814d6a9a7f42.png)

So double `<` inside `<html>` tag breaking export for some reason.
We are using `Release 2020-07-29 “Hogfather”`

**Comment by Klap-in** [comment]
The library we are using has a feature for this. This is implemented in the syntax of DokuWiki, see here how you can mark lines extra with e.g. `highlight_lines_extra="2,5"` https://www.dokuwiki.org/syntax_highlighting

I assume this style is exported to pdf as well (not tested).

**Comment by Stikus** [comment]
We need a mix of colors in one line, but thanks for the idea - I'll look into it in the future.

Am I correct that export behavior is not a bug and I should close this issue?

**Comment by Klap-in** [comment]
Escaping is the responsibility of the user of the pre-tags. So indeed no bug.
