### ISSUE TITLE
font-size Option in Configuration Manager do not work

### ISSUE THREAD

**Issue by sarotar2303** [splitbrain/dokuwiki-plugin-dw2pdf#460]
Hello,

after I have installed dw2pdf I wanted to change the font size because the size is a little bit to large in my exported PDF Files.
I tryed to change the the font-size Option in the Configuration Manager -> dw2pdf section -> font-size from 8 to 6 and after that to 4, saved the setting and retryed a export but nothing happened to the font size in the PDF File.

Do I make anything wrong?

**Comment by Klap-in** [comment]
Not yet tested, in the code it looks like the font info is forwarded to the library mPDF that should generate the pdf. 
For a bit more context: What are you exporting? Common text, or does it include plugins? Which template do you use, ‘dokuwiki’ or another one? Do you use another pdf template or just the default pdf template? Did you try other settings as well? Which version of DokuWiki do you use?

**Comment by sarotar2303** [comment]
I tried it with exporting both, just common text and an article with plugins like wrap, noprint and tag. The template that I have used was vector, but since it actually don´t work well with Version Igor I have tried it with the dokuwiki template and now with Sprintdoc, everytime with the same problem. I tried it with the default pdf template an a template on which I removed the Box with the QR Code and changed the Header and Footer. The exact Version of Dokuwiki that I use is 2022-07-31 "Igor".

**Comment by Qube2org** [comment]
I've the same issue on "Igor", with default pdf template, template for Dokuwiki is Sprintdoc.

**Comment by Klap-in** [comment]
it is a bug, we set `fontsize` as mpdf config setting, but that setting does not exist. It should be `default_font_size`.

**Comment by Klap-in** [comment]
You can try by reinstalling the plugin.

**Comment by sarotar2303** [comment]
I reinstalled the Plugin and now it seems to be working properly now.

Thank you!

Am Sa., 8. Okt. 2022 um 19:24 Uhr schrieb Gerrit Uitslag <
***@***.***>:
