### ISSUE TITLE
Local QR code generation

### ISSUE THREAD

**Issue by dipohl** [splitbrain/dokuwiki-plugin-dw2pdf#465]
As the current QR code generation using  online service https://quickchart.io/ makes problems with "Error 504 - Gateway Timeout" on servers behind a firewall, see #462, it would be nice to have the new feature of local generation of QR code.  @Klap-in said it
can be added with e.g. https://github.com/mpdf/qrcode 

It would also be a improvement in perspective of privacy :+1: 

For a start it would be nice if someone adds an expception handling concerning the Timeout Error so that dokuwiki admins get a speaking error message pointing to the concrete problem which one can solve by disabling QR code generation or a higher timeout value in Apache configuration.

**Comment by Klap-in** [comment]
Implemented by #482
