### ISSUE TITLE
Unable to decompress the downloaded file

### ISSUE THREAD

**Issue by j0hannes** [splitbrain/dokuwiki-plugin-dw2pdf#468]
I see the error message
`Unable to decompress the downloaded file. This maybe as a result of a bad download, in which case you should try again; or the compression format may be unknown, in which case you will need to download and install manually. Could not open file for writing: [...]data/tmp/5483089eb5849415d8bd50be86e97a1f/dw2pdf/splitbrain-dokuwiki-plugin-dw2pdf-8e03ab9/vendor/myclabs/deep-copy/.github/FUNDING.yml`
when trying to update the plugin. All other plugins could be updated without any problem.

**Comment by splitbrain** [comment]
This is the important part:

> Could not open file for writing:

Check your permissions on the data/tmp dir and ensure you have enough disk space.
