### ISSUE TITLE
Including output from MathJax?

### ISSUE THREAD

**Issue by ThSGM** [splitbrain/dokuwiki-plugin-dw2pdf#48]
Is there any way to include the processed output of LaTeX formulae generated using Mathjax (https://www.dokuwiki.org/plugin:mathjax)? At the moment, this output is just read as regular text.

**Comment by Klap-in** [comment]
There are some notes about mathjax in relation to mPDF library.
http://mpdf1.com/manual/index.php?tid=495

Pull requests welcome ;)
