### ISSUE TITLE
Multiline support of diagrams in PDF

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [splitbrain/dokuwiki-plugin-dw2pdf#480]
If a diagram, which is created by the diagrams plugin, contains a text element with several lines, there is a problem when generating PDF files with the dw2pdf plugin: 
There, only the first line with three attached dots is output then.

Example:
A diagram with this text:
![image](https://user-images.githubusercontent.com/1800472/227224286-06045b6f-6167-4007-af45-5e3d383a3a23.png)

becomes:
![image](https://user-images.githubusercontent.com/1800472/227224353-d2aada2d-57fb-43c1-af41-5c203a5e3dc8.png)

(I've put the same issue at the both plugins dw2pdf and diagrams)

Regards
Juergen

**Comment by splitbrain** [comment]
needs to be addressed in diagrams plugin
