### ISSUE TITLE
install does not work!

### ISSUE THREAD

**Issue by hfr** [splitbrain/dokuwiki-plugin-dw2pdf#491]
Installation results in the message:

Unable to download the file: https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master

**Comment by Klap-in** [comment]
Downloads fine for me. Sure you system can reach the site? Installing other plugins work? Please provide extra information about your system to make debugging possible. Are there logs?

**Comment by hfr** [comment]
I just tried:

curl "https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master"

I got: !!nothing!!

If there is nothing, then installation is not possible...

But it is still possible to download the master.zip from here, extract it and rename the directory. So the plugin works, just the easy-install using the link does not.

**Comment by splitbrain** [comment]
> curl "https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master"
>
> I got: !!nothing!!

Curl does not follow redirects by default. You would need the -L option for that.

Downloading works fine for me as well. Probably a problem at your side.

Closing this, since "does not work" is not an actionable bug report.

**Comment by hfr** [comment]
Sorry, I did not expect a redirect.

Probably the error message is missleading. Automatic installation for 20 other plugins work and I can get the master file with wget. So I can install everything else and I can manually install this plugin. So everything works for me and if nobody else has my problem then there is no problem.

**Comment by Klap-in** [comment]
The dw2pdf plugin has a download size around 50 MB (there are some fonts included), in the past there have been reports which indicated that some setups have difficulties with downloading that. But recently I have not seen reports about that.

**Comment by jakobdevey** [comment]
I am getting the same error: "Unable to download the file: https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master"

I had the plugin installed before and was having issues updating so I uninstalled the plugin but I get the same error when I try to re-install it. 

Has anyone found a solution yet?

**Comment by nerun** [comment]
Not working for me too. I have tried reinstall, and manual installation but don't works.

**Comment by splitbrain** [comment]
"does not work" is not an actionable bug report. @Klap-In already gave reasons why installation of this plugin might fail when others succeed, the large file size might result in timeouts on slow internet connections. You can always manually install the plugin.
