### ISSUE TITLE
Smileys issue - permissions issue

### ISSUE THREAD

**Issue by akarapatis** [splitbrain/dokuwiki-plugin-dw2pdf#72]
It seems that for smileys the image location passed to mPDF is the image URL and not a relative. For installations with restricted permissions that causes a problem and images cannot be referenced. 

Is it possible to set relative paths for smileys' images?

**Comment by mrclschstr** [comment]
Short addition: My Dokuwiki was running on IIS 8.5 with PHP 7.1 with enabled Windows authentication (SSO). The NTML authentication was the cause of missing images as dw2pdf doesn't seem to handle this appropiately. Switching to normal AD authentication with manual login solved the problem.
