### ISSUE TITLE
How to avoid pagebreaks in DW2PDF

### ISSUE THREAD

**Issue by ingof** [splitbrain/dokuwiki-plugin-dw2pdf#75]
Hello,

I use the WRAP-Plugin to avoid pagebreaks on long tables in printpreview.

In printpreview it works fine but in the exported PDF-file with DW2PDF it wont work.

How can i prevent pagebreaks in DW2PDF. For excample for long tables or textblocks wich belongs together?

**Comment by Klap-in** [comment]
My understanding is that to avoid pagebreaks, you have to set at blocks the CSS instruction `page-break-inside: avoid` (in case of dokuwiki the blocks are the `<p>` elements, which surround every section of the text)

https://mpdf.github.io/paging/page-breaks.html

I guess it is not desired to add this instruction to every `<p>` element. So I don't know how to improve this case.

**Comment by Klap-in** [comment]
I do not know how this in a convenient manner can be implemented. So therefore I propose to close this issue as wontfix.
