### ISSUE TITLE
[Wrap plugin] pagebreak works once but then is ignored

### ISSUE THREAD

**Issue by r0ckarong** [splitbrain/dokuwiki-plugin-dw2pdf#99]
I'm trying to insert manual page breaks into a long document to space it correctly. I'm using the wrap plugin with the "pagebreak" option. The first tag that I set gives me a correct pagebreak. Each following <WRAP pagebreak> tag is completely ignored and does not break the pages as expected. 

e.g. Example 1:

```
<WRAP pagebreak></WRAP>
content

<WRAP pagebreak></WRAP>
more content

even more content
```

Here the first "content" is broken onto a new page and "more content" rendered directly after it without a break. I would expect "more content" to be on a new page as well.

Example 2:
There is a weird effect with using an empty tag to break. Above if I only use empty <WRAP> tags to induce page breaks the first works and the second is ignored. The opposite happens when I use something like this:

```
<WRAP pagebreak></WRAP>

Content

<WRAP pagebreak>
more content
</WRAP>
```

In this case the empty tag is ignored and the one surrounding actual content works (page break occurs after "more content").

This feature is essential for me since I want to move our manual publishing to PDF export but without being able to control what content breaks where this is impossible.

**Comment by Klap-in** [comment]
Maybe a solution is to let the Wrap plugin use <pagebreak /> if it is rendered for the dw2pdf plugin. 

Pull request at the Wrap plugin is welcome!

**Comment by Klap-in** [comment]
Testing with 
```
======Title======

Text
<WRAP pagebreak></WRAP>
content

<WRAP pagebreak></WRAP>
more content

even more content

<WRAP pagebreak></WRAP>
content

<WRAP pagebreak></WRAP>
more content

even more content
```
Works fine for me. It creates exact 4 page breaks.
